-- CONSTRUCTIONS by AiXLuxury: Supabase schema. Apply as a migration.
create extension if not exists pgcrypto;
create type company_type as enum ('developer','construction_company','engineering','general_contractor','civil_engineering','structural_engineering','mep','architecture','infrastructure','specialized_contractor');
create type project_status as enum ('completed','under_construction','upcoming');
create type company_project_role as enum ('developer','general_contractor','architect','engineer','mep','project_manager','supplier','other');
create type lead_status as enum ('new','contacted','qualified','converted','closed','archived');
create type lead_type as enum ('company_inquiry','project_inquiry','company_onboarding','project_promotion','profile_claim');
create type opportunity_level as enum ('high','medium','low');

create table locations (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, county text, latitude numeric, longitude numeric, created_at timestamptz not null default now());
create table companies (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, type company_type not null, location_id uuid references locations, description text, founded_year smallint check (founded_year between 1800 and 2100), website text, contact_email text, contact_phone text, specializations text[] not null default '{}', services text[] not null default '{}', markets text[] not null default '{}', certifications text[] not null default '{}', is_featured boolean not null default false, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table company_timeline (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies on delete cascade, event_year smallint not null check(event_year between 1800 and 2100), title text not null, description text, verified_at timestamptz, created_at timestamptz not null default now());
create table projects (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, location_id uuid references locations, address text, latitude numeric, longitude numeric, status project_status not null, project_type text, description text, estimated_investment numeric, surface_area numeric, unit_count integer, estimated_completion date, current_progress_percent smallint check (current_progress_percent between 0 and 100), current_stage text check (current_stage in ('planning','permits','foundation','structure','facade','mep','finishing','delivered')), is_featured boolean not null default false, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table project_companies (project_id uuid not null references projects on delete cascade, company_id uuid not null references companies on delete cascade, role company_project_role not null, verified_at timestamptz, primary key(project_id,company_id,role));
create table project_progress (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects on delete cascade, stage text not null check(stage in ('planning','permits','foundation','structure','facade','mep','finishing','delivered')), percentage smallint check(percentage between 0 and 100), note text, verified_at timestamptz, created_at timestamptz not null default now());
create table media (id uuid primary key default gen_random_uuid(), company_id uuid references companies on delete cascade, project_id uuid references projects on delete cascade, storage_key text not null, alt_text text, media_type text not null check(media_type in ('image','video','document')), sort_order integer not null default 0, created_at timestamptz not null default now(), check (company_id is not null or project_id is not null));
create table leads (id uuid primary key default gen_random_uuid(), company_id uuid references companies, project_id uuid references projects, source text not null check(source in ('homepage','company_profile','project_profile','promote_company','promote_project','claim_profile','work_with_company','industry','search')), lead_type lead_type not null, request_type text, name text not null, company_name text, email text not null, phone text, message text, status lead_status not null default 'new', assigned_to uuid references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table lead_notes (id uuid primary key default gen_random_uuid(), lead_id uuid not null references leads on delete cascade, author_id uuid references auth.users, body text not null, created_at timestamptz not null default now());
create table profile_claims (id uuid primary key default gen_random_uuid(), company_slug text not null, claimant_name text not null, claimant_company text, email text not null, phone text, role text, website text, message text, status lead_status not null default 'new', reviewed_by uuid references auth.users, reviewed_at timestamptz, created_at timestamptz not null default now());
create table editorial_content (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, excerpt text, body jsonb, category text, published_at timestamptz, created_at timestamptz not null default now());
create table private_opportunity_scores (company_id uuid primary key references companies on delete cascade, website_quality smallint check(website_quality between 1 and 5), social_presence smallint check(social_presence between 1 and 5), project_visibility smallint check(project_visibility between 1 and 5), content_quality smallint check(content_quality between 1 and 5), brand_quality smallint check(brand_quality between 1 and 5), lead_generation_capability smallint check(lead_generation_capability between 1 and 5), opportunity opportunity_level, notes text, updated_at timestamptz not null default now());
create index companies_public_idx on companies(type, location_id) where published_at is not null;
create index projects_public_idx on projects(status, location_id) where published_at is not null;
create index leads_status_created_idx on leads(status, created_at desc);

alter table companies enable row level security; alter table projects enable row level security; alter table locations enable row level security; alter table company_timeline enable row level security; alter table project_companies enable row level security; alter table project_progress enable row level security; alter table media enable row level security; alter table editorial_content enable row level security; alter table leads enable row level security; alter table lead_notes enable row level security; alter table profile_claims enable row level security; alter table private_opportunity_scores enable row level security;
create policy "published companies are readable" on companies for select using (published_at is not null);
create policy "published projects are readable" on projects for select using (published_at is not null);
create policy "locations are readable" on locations for select using (true);
create policy "published editorial is readable" on editorial_content for select using (published_at is not null);
-- No public policy is granted for leads, claims, notes, or opportunity scores. Admin access is provided through a server-only service role or dedicated authenticated policies.
