'use client';
import { FormEvent, useState } from 'react';
type LeadKind = 'work' | 'promote' | 'project';
export function LeadForm({kind,company,source='work_with_company'}:{kind:LeadKind;company?:string;source?:string}) {
 const [state,setState]=useState<'idle'|'sending'|'sent'|'error'>('idle'); const [message,setMessage]=useState('');
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setState('sending');const form=new FormData(event.currentTarget);const response=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),company:form.get('company'),email:form.get('email'),phone:form.get('phone'),requestType:form.get('requestType'),message:form.get('message'),source,leadType:kind==='work'?'company_inquiry':kind==='project'?'project_promotion':'company_onboarding'})});const data=await response.json();if(!response.ok){setMessage(data.error);setState('error');return}setState('sent')};
 if(state==='sent') return <p className="form-status" role="status">Thank you. Your request has been recorded for follow-up.</p>;
 const options=kind==='work'?['Construction','Development','Engineering','Architecture','Partnership','Supplier','Investment','Other']:kind==='project'?['Project website','Landing page','Photography','Video','Drone','Social media','Paid advertising','SEO','Lead generation','Full campaign']:['Website','Branding','Project promotion','Photography','Video','Social media','SEO','Lead generation','Full digital presence'];
 return <form className="form-grid" onSubmit={submit} noValidate><label><span className="form-label">Name</span><input name="name" required autoComplete="name" placeholder="Name *"/></label><label><span className="form-label">Company</span><input name="company" autoComplete="organization" placeholder="Company"/></label><label><span className="form-label">Business email</span><input name="email" required type="email" autoComplete="email" placeholder="Business email *"/></label><label><span className="form-label">Phone</span><input name="phone" autoComplete="tel" placeholder="Phone"/></label>{company&&<label className="full"><span className="form-label">Selected company</span><input className="full" value={company} readOnly aria-label="Selected company"/></label>}<label className="full"><span className="form-label">Request</span><select name="requestType" required defaultValue=""><option value="" disabled>Choose a service or request type *</option>{options.map(x=><option key={x}>{x}</option>)}</select></label><label className="full"><span className="form-label">Message</span><textarea name="message" placeholder="Tell us more about your request"/></label>{state==='error'&&<p className="form-error full" role="alert">{message}</p>}<button className="btn fill full" disabled={state==='sending'} type="submit">{state==='sending'?'Sending…':kind==='work'?'Send request':'Get started'}</button></form>;
}
