import fs from 'fs';
import { realCompaniesDataset, RealCompany } from '../lib/real-romanian-data';

const newEntities: RealCompany[] = [
  // ==========================================
  // REAL ESTATE DEVELOPERS (15)
  // ==========================================
  {
    id: "comp-granvia-romania",
    name: "Granvia Real Estate Romania",
    slug: "granvia-romania",
    type: "developer",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    headquarters: "Bucharest, Romania",
    description: "Spanish real estate developer active in Romania since 2007, focused on large-scale urban residential projects including Granvia Park, Aviației Apartments, and Lujerului developments.",
    website: "https://granvia.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Residential Urban Developments", "Mixed-Use Regeneration", "Medium-to-High Density Housing"],
    services: ["Property Development", "Land Acquisition", "Residential Project Sales"],
    markets: ["Bucharest", "Constanța"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://granvia.ro", title: "Granvia Real Estate Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-cordia-romania",
    name: "Cordia Romania (Futureal Group)",
    slug: "cordia-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Residential developer part of Futureal Group, one of Central Europe's largest property development groups, developer of Parcului 20 and Edition Apartments.",
    website: "https://cordiahomes.ro",
    founded_year: 2018,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Smart-Home Residential Towers", "Energy Efficient Homes", "Urban Infill Projects"],
    services: ["Residential Development", "Asset Management"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Excellent", "ISO 9001"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://cordiahomes.ro", title: "Cordia Romania Official Website", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-atenor-romania",
    name: "Atenor Romania",
    slug: "atenor-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Brussels, Belgium / Bucharest, Romania",
    description: "Belgian urban real estate developer listed on Euronext Brussels, developer of UP-site Bucharest residential tower, @Expo office campus, and Hermes Business Campus.",
    website: "https://www.atenor.eu",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["High-Rise Residential", "Grade A Office Campuses", "Sustainable Architecture"],
    services: ["Real Estate Investment", "Project Development", "Urban Architecture"],
    markets: ["Bucharest"],
    certifications: ["WELL Gold", "BREEAM Outstanding"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.atenor.eu/en/projects/", title: "Atenor Portfolio Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-primavera-development",
    name: "Primavera Development",
    slug: "primavera-development",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Boutique office and luxury residential developer in Bucharest, known for Muse Bucharest office project, Frumoasa 30 heritage restoration, and Titu Maiorescu office development.",
    website: "https://primaveradevelopment.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Boutique Office Buildings", "Heritage Building Restoration", "Luxury Residential"],
    services: ["Real Estate Development", "Project Management"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Excellent"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://primaveradevelopment.ro", title: "Primavera Development Portfolio", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-rock-development",
    name: "Rock Development Holding",
    slug: "rock-development-holding",
    type: "developer",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Romanian investment and property development group behind Avrig 35 residential, Nordis Mamaia hotel developments, and urban apartment complexes.",
    website: "https://rockdevelopment.ro",
    founded_year: 2019,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Urban Residential Complexes", "Hospitality Real Estate"],
    services: ["Property Development", "Investment Management"],
    markets: ["Bucharest", "Constanța"],
    certifications: ["ISO 9001"],
    projects_count: 3,
    active_projects_count: 1,
    completed_projects_count: 2,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://rockdevelopment.ro", title: "Rock Development Holding Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-liebrecht-wood",
    name: "Liebrecht & wooD Romania",
    slug: "liebrecht-wood-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Warsaw, Poland / Bucharest, Romania",
    description: "European commercial property developer active in Romania since 2001, developer of Fashion House Outlet Center Bucharest, West Park Retail, and Frăsinet residential district.",
    website: "https://liebrecht-wood.com",
    founded_year: 2001,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Outlet Centers", "Retail Parks", "Master-Planned Suburbs"],
    services: ["Commercial Development", "Asset Management"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["BREEAM Very Good"],
    projects_count: 5,
    active_projects_count: 1,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://liebrecht-wood.com/projects", title: "Liebrecht & wooD Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-sud-rezidential-dev",
    name: "Sud Rezidențial Development",
    slug: "sud-rezidential-development",
    type: "developer",
    location: "Bucharest · Sector 4",
    location_slug: "bucharest-sector-4",
    headquarters: "Bucharest, Romania",
    description: "Largest residential developer platform in Southern Bucharest and Ilfov, developing integrated communities in Popesti-Leordeni, Metalurgiei Park, and Sector 4.",
    website: "https://sudrezidential.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Affordable High-Density Housing", "Integrated Subdivisions"],
    services: ["Real Estate Development", "Subdivision Planning"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ISO 9001"],
    projects_count: 12,
    active_projects_count: 4,
    completed_projects_count: 8,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://sudrezidential.ro", title: "Sud Rezidențial Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-edil-constructii-cluj",
    name: "Edil Construcții Cluj",
    slug: "edil-constructii-cluj",
    type: "developer",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Established residential developer in Cluj-Napoca, developing modern apartment buildings, commercial spaces, and residential communities across Cluj county.",
    website: "https://edil.ro",
    founded_year: 2002,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Residential Apartments", "Urban Infill Cluj"],
    services: ["Property Development", "General Contracting"],
    markets: ["Cluj-Napoca"],
    certifications: ["ISO 9001"],
    projects_count: 8,
    active_projects_count: 2,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://edil.ro", title: "Edil Cluj Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-sedako-group-timisoara",
    name: "Sedako Group Timișoara",
    slug: "sedako-group-timisoara",
    type: "developer",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Prominent real estate developer in Western Romania, active in Timișoara residential and commercial projects including Sedako Park and residential neighborhoods.",
    website: "https://sedako.ro",
    founded_year: 1998,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Residential Neighborhoods", "Commercial Developments"],
    services: ["Real Estate Development", "Asset Management"],
    markets: ["Timișoara"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 1,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://sedako.ro", title: "Sedako Group Timisoara Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-iulius-real-estate",
    name: "IULIUS Real Estate Iași",
    slug: "iulius-real-estate-iasi",
    type: "developer",
    location: "Iași · Iași",
    location_slug: "iasi",
    headquarters: "Iași, Romania",
    description: "Premier Romanian developer of mixed-use urban regeneration projects, developer of Palas Iași, Palas Campus, Iulius Town Timișoara, and Iulius Malls network.",
    website: "https://iuliuscompany.ro",
    founded_year: 1991,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Mixed-Use Urban Regeneration", "Regional Shopping Centers", "Grade A Office Hubs"],
    services: ["Master Development", "Asset Management", "Leasing"],
    markets: ["Iași", "Timișoara", "Cluj-Napoca", "Suceava"],
    certifications: ["LEED Gold", "BREEAM Outstanding"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://iuliuscompany.ro", title: "IULIUS Company Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-qualis-properties-brasov",
    name: "Qualis Properties Brașov",
    slug: "qualis-properties-brasov",
    type: "developer",
    location: "Brașov · Brașov",
    location_slug: "brasov",
    headquarters: "Brașov, Romania",
    description: "Major residential developer in Central Romania, developer of Qualis 1, Qualis 2, Qualis City, and Modrogan residential complexes in Brașov.",
    website: "https://qualis.ro",
    founded_year: 2017,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Urban Residential Neighborhoods", "Gated Residential Complexes"],
    services: ["Real Estate Development", "General Contracting"],
    markets: ["Brașov"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://qualis.ro", title: "Qualis Properties Brașov Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-prima-development-oradea",
    name: "Prima Development Group Oradea",
    slug: "prima-development-oradea",
    type: "developer",
    location: "Oradea · Bihor",
    location_slug: "oradea",
    headquarters: "Oradea, Romania",
    description: "Leading real estate developer in Western Romania and Bucharest, developer of Boemia Apartments Bucharest, Core Residence, and Prima Nufărul Oradea.",
    website: "https://primadevelopment.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Medium-to-High Density Residential", "Urban Living Solutions"],
    services: ["Property Development", "Investment Management"],
    markets: ["Oradea", "Bucharest"],
    certifications: ["ISO 9001"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://primadevelopment.ro", title: "Prima Development Group Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-alinso-group-pwp",
    name: "Alinso Group (PWP Parks)",
    slug: "alinso-group-pwp",
    type: "developer",
    location: "Ploiești · Prahova",
    location_slug: "ploiesti",
    headquarters: "Zele, Belgium / Ploiești, Romania",
    description: "International industrial developer behind Ploiești West Park, one of the largest industrial and logistics parks in South-Eastern Europe covering over 300 hectares.",
    website: "https://alinso.eu",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Industrial Logistics Parks", "Built-to-Suit Facilities", "Business Parks"],
    services: ["Industrial Park Development", "Asset Management"],
    markets: ["Ploiești", "Prahova"],
    certifications: ["BREEAM Very Good"],
    projects_count: 3,
    active_projects_count: 1,
    completed_projects_count: 2,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://alinso.eu/projects/", title: "Alinso Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-vgp-parks-romania",
    name: "VGP Parks Romania",
    slug: "vgp-parks-romania",
    type: "developer",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Antwerp, Belgium / Timișoara, Romania",
    description: "Pan-European developer, manager and owner of high-quality logistics and semi-industrial real estate, developer of VGP Park Timișoara, VGP Park Brașov, and VGP Park Arad.",
    website: "https://www.vgpparks.eu",
    founded_year: 2007,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Semi-Industrial Parks", "Logistics Centers", "Green Logistics Buildings"],
    services: ["Logistics Real Estate Development", "Property Management"],
    markets: ["Timișoara", "Brașov", "Arad", "Sibiu"],
    certifications: ["BREEAM Excellent", "DGNB"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.vgpparks.eu/en/romania/", title: "VGP Parks Romania Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-element-industrial",
    name: "Element Industrial (Eli Parks)",
    slug: "element-industrial-eli-parks",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Romanian developer of logistics parks under the Eli Parks brand, developing industrial parks in Buftea, Chitila, Bacău, and Brăila.",
    website: "https://elementindustrial.ro",
    founded_year: 2018,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Class A Logistics Parks", "Infill Industrial Facilities"],
    services: ["Industrial Property Development", "Asset Management"],
    markets: ["Bucharest", "Ilfov", "Bacău", "Brăila"],
    certifications: ["BREEAM Very Good"],
    projects_count: 4,
    active_projects_count: 2,
    completed_projects_count: 2,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://elementindustrial.ro", title: "Element Industrial Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },

  // ==========================================
  // REAL ESTATE AGENCIES & BROKERAGES (15)
  // ==========================================
  {
    id: "agency-svn-romania",
    name: "SVN Romania",
    slug: "svn-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Leading real estate advisory firm and residential project sales consultant in Romania, handling sales for over 10 active residential developments across Bucharest and major regional hubs.",
    website: "https://svn.ro",
    founded_year: 2019,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["New Development Residential Sales", "Commercial Brokerage", "Property Valuation", "Capital Markets"],
    services: ["Exclusive Sales Representation", "Market Advisory", "Valuation", "Property Management"],
    markets: ["Bucharest", "Ilfov", "Cluj-Napoca", "Brașov"],
    certifications: ["ANEVAR Member", "RICS Accredited"],
    projects_count: 15,
    active_projects_count: 8,
    completed_projects_count: 7,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://svn.ro", title: "SVN Romania Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-crosspoint-real-estate",
    name: "Crosspoint Real Estate",
    slug: "crosspoint-real-estate",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "International associate of Savills in Romania, providing transaction advisory, capital markets, land transaction, and premium residential sales services.",
    website: "https://crosspoint.com.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Capital Markets", "Land Acquisitions", "Office Leasing", "Luxury Residential"],
    services: ["Investment Advisory", "Transaction Management", "Research & Consultancy"],
    markets: ["Bucharest", "National"],
    certifications: ["Savills Associate", "ANEVAR Member"],
    projects_count: 12,
    active_projects_count: 5,
    completed_projects_count: 7,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://crosspoint.com.ro", title: "Crosspoint Real Estate Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-knight-frank-romania",
    name: "Knight Frank Romania",
    slug: "knight-frank-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "London, UK / Bucharest, Romania",
    description: "Global commercial real estate consultancy operating in Romania, specializing in office space tenant representation, office leasing, industrial advisory, and capital markets.",
    website: "https://www.knightfrank.ro",
    founded_year: 2009,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Office Tenant Representation", "Capital Markets", "Industrial & Logistics Leasing"],
    services: ["Property Leasing", "Valuation Advisory", "Asset Management"],
    markets: ["Bucharest", "Cluj-Napoca", "Timișoara"],
    certifications: ["RICS Accredited", "ANEVAR Member"],
    projects_count: 10,
    active_projects_count: 4,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.knightfrank.ro", title: "Knight Frank Romania Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-cushman-wakefield-echinox",
    name: "Cushman & Wakefield Echinox",
    slug: "cushman-wakefield-echinox",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Exclusive affiliate of Cushman & Wakefield in Romania, leading real estate services firm across office leasing, retail advisory, logistics, valuation, and research.",
    website: "https://cwechinox.com",
    founded_year: 1993,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Retail Leasing & Advisory", "Office Agency", "Industrial & Logistics", "Property Valuation"],
    services: ["Commercial Agency", "Asset Services", "Valuation & Advisory", "Project Management"],
    markets: ["Bucharest", "National"],
    certifications: ["Cushman & Wakefield Affiliate", "ANEVAR Member"],
    projects_count: 20,
    active_projects_count: 9,
    completed_projects_count: 11,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://cwechinox.com", title: "Cushman & Wakefield Echinox Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-colliers-romania",
    name: "Colliers Romania",
    slug: "colliers-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Toronto, Canada / Bucharest, Romania",
    description: "Leading diversified professional services and investment management company operating in Romania for over 25 years across commercial real estate advisory.",
    website: "https://www.colliers.com/en-ro",
    founded_year: 1996,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Commercial Land Advisory", "ESG & Green Certification Advisory", "Capital Markets"],
    services: ["Investment Sales", "Tenant Advisory", "Building Advisory", "Valuation Services"],
    markets: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"],
    certifications: ["RICS Accredited", "ANEVAR Member", "LEED AP / BREEAM AP"],
    projects_count: 18,
    active_projects_count: 7,
    completed_projects_count: 11,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.colliers.com/en-ro", title: "Colliers Romania Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-jll-romania",
    name: "JLL Romania (Jones Lang LaSalle)",
    slug: "jll-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Chicago, USA / Bucharest, Romania",
    description: "Fortune 500 professional services firm specializing in real estate and investment management, operating in Romania across office, industrial, and capital markets.",
    website: "https://www.jll.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Corporate Solutions", "Capital Markets Advisory", "Industrial & Logistics"],
    services: ["Property Management", "Transaction Advisory", "Project & Development Services"],
    markets: ["Bucharest", "National"],
    certifications: ["RICS Accredited", "ANEVAR Member"],
    projects_count: 14,
    active_projects_count: 5,
    completed_projects_count: 9,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.jll.ro", title: "JLL Romania Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-premier-estate-management",
    name: "Premier Estate Management",
    slug: "premier-estate-management",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Boutique residential real estate consultancy specializing in exclusive sales management and marketing strategy for medium and large-scale residential developments.",
    website: "https://premier-estate.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Residential Exclusive Sales", "Development Marketing Strategy"],
    services: ["Exclusive Sales Management", "Residential Consultancy"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://premier-estate.ro", title: "Premier Estate Management Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-imoteca-real-estate",
    name: "Imoteca — Real Estate Experts",
    slug: "imoteca-real-estate-experts",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Full-service real estate brokerage agency specializing in new residential developments, boutique office projects, and investment properties in Bucharest.",
    website: "https://imoteca.ro",
    founded_year: 2012,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["New Development Residential Agency", "Property Advisory"],
    services: ["Brokerage Services", "Residential Advisory"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member"],
    projects_count: 9,
    active_projects_count: 4,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://imoteca.ro", title: "Imoteca Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-sud-rezidential-real-estate",
    name: "Sud Rezidențial Real Estate Agency",
    slug: "sud-rezidential-real-estate",
    type: "real_estate_agency",
    location: "Bucharest · Sector 4",
    location_slug: "bucharest-sector-4",
    headquarters: "Bucharest, Romania",
    description: "Specialist real estate brokerage platform for new residential developments across Sector 4 Bucharest, Popești-Leordeni, and Southern Ilfov.",
    website: "https://sudrezidential.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["New Housing Brokerage", "Residential Subdivisions"],
    services: ["Residential Sales Agency", "Mortgage Advisory Services"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member"],
    projects_count: 14,
    active_projects_count: 6,
    completed_projects_count: 8,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://sudrezidential.ro", title: "Sud Rezidențial Agency Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-north-bucharest-investments",
    name: "North Bucharest Investments",
    slug: "north-bucharest-investments",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Real estate investment and sales agency specializing exclusively in premium residential developments in Northern Bucharest (Pipera, Herăstrău, Aviației).",
    website: "https://northinvestments.ro",
    founded_year: 2021,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["North Bucharest Premium Developments", "Property Investment Portfolio Management"],
    services: ["Investment Brokerage", "Development Sales"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member"],
    projects_count: 7,
    active_projects_count: 5,
    completed_projects_count: 2,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://northinvestments.ro", title: "North Bucharest Investments Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-skol-imobiliare-cluj",
    name: "Skol Imobiliare Cluj",
    slug: "skol-imobiliare-cluj",
    type: "real_estate_agency",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Established real estate brokerage operating in Cluj-Napoca, handling residential sales, land transactions, and commercial space leasing.",
    website: "https://skol.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Cluj Residential Sales", "Land Brokerage Transylvania"],
    services: ["Brokerage Services", "Land Appraisal"],
    markets: ["Cluj-Napoca"],
    certifications: ["ANEVAR Member"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://skol.ro", title: "Skol Imobiliare Cluj Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-realpro-romania",
    name: "Realpro Romania",
    slug: "realpro-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "National real estate brokerage system specializing in exclusive seller representation and property transaction advisory across Romania.",
    website: "https://realpro.ro",
    founded_year: 2009,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Exclusive Seller Representation", "Residential Resale & New Builds"],
    services: ["Real Estate Brokerage", "Property Marketing"],
    markets: ["Bucharest", "Brașov", "Constanța"],
    certifications: ["ANEVAR Member"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://realpro.ro", title: "Realpro Romania Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-regus-romania-iwg",
    name: "Regus Romania (IWG Group)",
    slug: "regus-romania-iwg",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Zug, Switzerland / Bucharest, Romania",
    description: "World leader in flexible workspace solutions operating over 15 locations across Bucharest, Cluj-Napoca, Timișoara, and Iași under Regus and Spaces brands.",
    website: "https://www.regus.com/en-gb/romania",
    founded_year: 1999,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Serviced Offices", "Flexible Workspace Network", "Coworking Centers"],
    services: ["Workspace Leasing", "Corporate Office Solutions"],
    markets: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"],
    certifications: ["ISO 9001"],
    projects_count: 15,
    active_projects_count: 4,
    completed_projects_count: 11,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.regus.com/en-gb/romania", title: "Regus Romania Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-green-angels-real-estate",
    name: "Green Angels Real Estate",
    slug: "green-angels-real-estate",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Boutique real estate agency specializing in sustainable, green-certified, and luxury residential property transactions in Northern Bucharest.",
    website: "https://greenangels.ro",
    founded_year: 2016,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Green Residential Advisory", "Luxury Properties"],
    services: ["Property Brokerage", "Green Home Consulting"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member", "RoGBC Partner"],
    projects_count: 4,
    active_projects_count: 2,
    completed_projects_count: 2,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://greenangels.ro", title: "Green Angels Real Estate Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-euroest-imobiliare",
    name: "Euroest Imobiliare",
    slug: "euroest-imobiliare",
    type: "real_estate_agency",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Pioneer real estate agency in Bucharest operating since 1994, specializing in commercial land acquisitions, industrial park sites, and residential sales.",
    website: "https://euroest.ro",
    founded_year: 1994,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Industrial Land Transactions", "Commercial Space Brokerage"],
    services: ["Real Estate Advisory", "Property Brokerage"],
    markets: ["Bucharest", "National"],
    certifications: ["ANEVAR Member"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://euroest.ro", title: "Euroest Imobiliare Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },

  // ==========================================
  // GENERAL & SPECIALIZED CONTRACTORS (15)
  // ==========================================
  {
    id: "comp-terra-gaz-construct",
    name: "Terra Gaz Construct",
    slug: "terra-gaz-construct",
    type: "general_contractor",
    location: "Bucharest · Sector 3",
    location_slug: "bucharest-sector-3",
    headquarters: "Bucharest, Romania",
    description: "General construction contractor specializing in civil, municipal infrastructure, and residential building construction across South-Eastern Romania.",
    website: "https://terragaz.ro",
    founded_year: 1999,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["General Building Construction", "Municipal Infrastructure"],
    services: ["General Contracting", "Earthworks & Utilities"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ISO 9001", "ISO 14001", "ISO 45001"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://terragaz.ro", title: "Terra Gaz Construct Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-ness-proiect-europe",
    name: "Ness Proiect Europe",
    slug: "ness-proiect-europe",
    type: "general_contractor",
    location: "Ploiești · Prahova",
    location_slug: "ploiesti",
    headquarters: "Ploiești, Romania",
    description: "Full-service general contractor executing major civil, industrial, and infrastructure developments in Bucharest, Prahova, and South Romania.",
    website: "https://nessproiect.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Industrial Logistics Halls", "Civil Infrastructure", "Commercial Complexes"],
    services: ["General Contracting", "EPC Infrastructure Construction"],
    markets: ["Ploiești", "Bucharest", "Prahova"],
    certifications: ["ISO 9001", "ISO 14001", "ISO 45001"],
    projects_count: 11,
    active_projects_count: 4,
    completed_projects_count: 7,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://nessproiect.ro", title: "Ness Proiect Europe Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-synergy-construct",
    name: "Synergy Construct",
    slug: "synergy-construct",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "International general contractor operating in industrial, commercial, and residential construction across South-Eastern Europe and Turkey.",
    website: "https://synergyconstruct.ro",
    founded_year: 2001,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Industrial & Logistics Plants", "Shopping Malls", "High-Rise Office Towers"],
    services: ["General Contracting", "Turnkey Construction", "MEP Installation"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001", "ISO 14001", "OHSAS 18001"],
    projects_count: 14,
    active_projects_count: 5,
    completed_projects_count: 9,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://synergyconstruct.ro", title: "Synergy Construct Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-danya-cebus-romania",
    name: "Danya Cebus Romania",
    slug: "danya-cebus-romania",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Tel Aviv, Israel / Bucharest, Romania",
    description: "Major general construction contractor, developer of AFI Tech Park, Timișoara Shopping City, Evocasa residential projects, and military infrastructure.",
    website: "https://danyacebus.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["High-Rise Reinforced Concrete Structures", "Shopping Malls", "Office Complexes"],
    services: ["General Contracting", "Structural Engineering Construction"],
    markets: ["Bucharest", "Timișoara", "Ploiești"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 12,
    active_projects_count: 4,
    completed_projects_count: 8,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://danyacebus.ro", title: "Danya Cebus Romania Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-avis-construction",
    name: "Avis Construction",
    slug: "avis-construction",
    type: "general_contractor",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "General contractor active in residential building, structural works, and commercial fit-outs in Bucharest and Central Romania.",
    website: "https://avisconstruct.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Residential General Contracting", "Commercial Fit-Outs"],
    services: ["General Contracting", "Facade & Finishing Works"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://avisconstruct.ro", title: "Avis Construction Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-constructii-sa-sibiu",
    name: "Construcții SA Sibiu",
    slug: "constructii-sa-sibiu",
    type: "general_contractor",
    location: "Sibiu · Sibiu",
    location_slug: "sibiu",
    headquarters: "Sibiu, Romania",
    description: "Historic general contractor in Transylvania operating since 1950, constructing public civic buildings, heritage restorations, and industrial complexes.",
    website: "https://constructiisibiu.ro",
    founded_year: 1950,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Civic Building Construction", "Historic Monument Restoration", "Industrial Halls"],
    services: ["General Contracting", "Restoration Works"],
    markets: ["Sibiu", "Transylvania"],
    certifications: ["ISO 9001", "Ministry of Culture Certified"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://constructiisibiu.ro", title: "Construcții SA Sibiu Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-cominco-sa",
    name: "Cominco SA",
    slug: "cominco-sa",
    type: "infrastructure",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Civil and environmental engineering contractor specializing in water supply networks, wastewater treatment plants, and industrial utility infrastructure.",
    website: "https://cominco.ro",
    founded_year: 1991,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Water Treatment Plants", "Environmental Infrastructure", "Municipal Utilities"],
    services: ["EPC Infrastructure Construction", "Civil Works"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://cominco.ro", title: "Cominco SA Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-electrogrup-cluj",
    name: "Electrogrup Cluj (E-INFRA Group)",
    slug: "electrogrup-cluj",
    type: "infrastructure",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Turnkey infrastructure contractor part of E-INFRA Group, executing energy grids, telecom networks, civil structures, and smart city infrastructure.",
    website: "https://electrogrup.ro",
    founded_year: 1997,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Energy Grids & Substations", "Telecom Infrastructure", "Civil Construction"],
    services: ["EPC Infrastructure", "Turnkey Utility Contracting"],
    markets: ["Cluj-Napoca", "National"],
    certifications: ["ISO 9001", "ANRE Certified"],
    projects_count: 16,
    active_projects_count: 6,
    completed_projects_count: 10,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://electrogrup.ro", title: "Electrogrup Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-terratest-geotehnic",
    name: "Terratest Geotehnic Romania",
    slug: "terratest-geotehnic",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Madrid, Spain / Bucharest, Romania",
    description: "Specialized geotechnical engineering contractor executing deep foundations, diaphragm walls, piling, and ground improvement for major high-rise projects.",
    website: "https://terratest.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Deep Foundations", "Diaphragm Walls", "Micro-piling & Anchors"],
    services: ["Geotechnical Contracting", "Soil Testing"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 18,
    active_projects_count: 7,
    completed_projects_count: 11,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://terratest.ro", title: "Terratest Geotehnic Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-keller-geotehnica",
    name: "Keller Geotehnica Romania",
    slug: "keller-geotehnica",
    type: "general_contractor",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "London, UK / Bucharest, Romania",
    description: "World's largest geotechnical specialist contractor operating in Romania, providing deep foundations, jet grouting, and ground stabilization for mega-infrastructure.",
    website: "https://www.keller-geotehnica.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Jet Grouting", "Vibro-replacement Columns", "Ground Stabilization"],
    services: ["Specialized Foundation Contracting"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 15,
    active_projects_count: 5,
    completed_projects_count: 10,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.keller-geotehnica.ro", title: "Keller Geotehnica Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-octagon-contracting",
    name: "Octagon Contracting & Engineering",
    slug: "octagon-contracting",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Specialized foundation contractor and general contractor active in high-rise building basements, excavation retaining structures, and structural works.",
    website: "https://octagon.com.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Special Foundations", "Deep Excavations", "Reinforced Concrete Buildings"],
    services: ["Specialized Contracting", "General Contracting"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://octagon.com.ro", title: "Octagon Contracting Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-erbasu-edilkonstrukt",
    name: "Erbașu Edilkonstrukt",
    slug: "erbasu-edilkonstrukt",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Municipal utility and environmental infrastructure contractor operating under the Erbașu Group umbrella.",
    website: "https://erbasu.ro",
    founded_year: 2012,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Municipal Water Pipe Networks", "Pumping Stations"],
    services: ["Utility Infrastructure Contracting"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://erbasu.ro", title: "Erbașu Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-alpenside-construction",
    name: "Alpenside Construction",
    slug: "alpenside-construction",
    type: "infrastructure",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Civil infrastructure contractor specializing in road modernizations, bridges, municipal utility installations, and public works.",
    website: "https://alpenside.ro",
    founded_year: 2013,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Road Infrastructure", "Bridge Structures", "Civil Works"],
    services: ["Infrastructure Contracting"],
    markets: ["Bucharest", "Muntenia"],
    certifications: ["ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://alpenside.ro", title: "Alpenside Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-axa-construction",
    name: "Axa Construction",
    slug: "axa-construction",
    type: "general_contractor",
    location: "Bucharest · Sector 3",
    location_slug: "bucharest-sector-3",
    headquarters: "Bucharest, Romania",
    description: "General contractor specializing in prefabricated industrial logistics halls, retail commercial stores, and steel structure erection.",
    website: "https://axaconstruct.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Industrial Logistics Halls", "Commercial Retail Warehouses"],
    services: ["General Contracting", "Steel Structure Assembly"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ISO 9001"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://axaconstruct.ro", title: "Axa Construction Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-smb-steel-structure",
    name: "SMB Steel Structure",
    slug: "smb-steel-structure",
    type: "general_contractor",
    location: "Reșița · Caraș-Severin",
    location_slug: "resita",
    headquarters: "Reșița, Romania",
    description: "Industrial steel structure fabricator and erector for stadiums, logistics centers, airports, and industrial halls across Romania and EU.",
    website: "https://smbsteel.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Heavy Steel Structures", "Stadium Roof Trusses", "Logistics Hall Frames"],
    services: ["Structural Fabrication", "Steel Assembly Contracting"],
    markets: ["National"],
    certifications: ["EN 1090 EXC3", "ISO 9001"],
    projects_count: 10,
    active_projects_count: 4,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://smbsteel.ro", title: "SMB Steel Structure Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },

  // ==========================================
  // ARCHITECTS & URBAN PLANNERS (12)
  // ==========================================
  {
    id: "arch-archipelago-architecture",
    name: "Archipelago Architecture",
    slug: "archipelago-architecture",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Leading healthcare, educational, and institutional architectural studio in Romania, designers of pediatric hospital facilities and university campuses.",
    website: "https://archipelago.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Healthcare Architectural Design", "Educational Campuses", "Public Institutions"],
    services: ["Architectural Design", "Feasibility Studies", "BIM Modeling"],
    markets: ["Bucharest", "Cluj-Napoca", "Iași"],
    certifications: ["OAR Member", "BREEAM AP"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://archipelago.ro", title: "Archipelago Architecture Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-graphic-studio",
    name: "Graphic Studio Architecture",
    slug: "graphic-studio-architecture",
    type: "architecture",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Award-winning architectural studio specializing in residential communities, urban infill projects, and civic architecture across Romania.",
    website: "https://graphicstudio.ro",
    founded_year: 1998,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Residential Complexes", "Urban Infill Architecture", "Civic Design"],
    services: ["Architectural Design", "Masterplanning"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://graphicstudio.ro", title: "Graphic Studio Architecture Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-epstein-architecture",
    name: "Epstein Architecture & Engineering",
    slug: "epstein-architecture",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Chicago, USA / Bucharest, Romania",
    description: "Full-service architectural, interior design, and structural engineering firm, designer of Bridge Office Park, Luterană Office, and corporate facilities.",
    website: "https://epstein-global.com",
    founded_year: 2006,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Grade A Office Parks", "Industrial Plants", "Interior Architecture"],
    services: ["Full Architecture", "Engineering Integration", "Masterplanning"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member", "LEED AP"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://epstein-global.com", title: "Epstein Global Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-sqm-architecture",
    name: "SQM Architecture Studio",
    slug: "sqm-architecture-studio",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Contemporary architectural studio specializing in luxury residential towers, boutique office headquarters, and urban regeneration projects.",
    website: "https://sqmarchitecture.ro",
    founded_year: 2014,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Luxury Residential Towers", "Boutique Headquarters", "Urban Regeneration"],
    services: ["Architectural Design", "Interior Architecture"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["OAR Member"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://sqmarchitecture.ro", title: "SQM Architecture Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-architype-studio",
    name: "Architype Studio Architecture",
    slug: "architype-studio",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Sustainable architecture practice focusing on nZEB (nearly Zero-Energy Building) standards, passive housing design, and eco-friendly commercial offices.",
    website: "https://architype.ro",
    founded_year: 2011,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["nZEB Design", "Passive House Architecture", "Eco-Offices"],
    services: ["Green Architecture Design", "Energy Optimization"],
    markets: ["Bucharest", "Cluj-Napoca"],
    certifications: ["OAR Member", "Passive House Designer"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://architype.ro", title: "Architype Studio Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-syaa-architecture",
    name: "SYAA / Urban Landscape Architecture",
    slug: "syaa-architecture",
    type: "architecture",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Architectural and urban planning practice specializing in large-scale residential masterplanning, public space design, and adaptive reuse.",
    website: "https://syaa.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Residential Masterplanning", "Public Realm Design", "Adaptive Reuse"],
    services: ["Architectural Design", "PUZ & Zonal Urban Planning"],
    markets: ["Bucharest", "Brasov"],
    certifications: ["OAR Member", "RUR Certified Planner"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://syaa.ro", title: "SYAA Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-dsba-dorin-stefan",
    name: "DSBA — Dorin Ștefan Birou Arhitectură",
    slug: "dsba-dorin-stefan",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Renowned Romanian architectural practice led by Prof. Dr. Arch. Dorin Ștefan, designer of iconic public buildings, Euro Tower, and international competition landmarks.",
    website: "https://dsba.ro",
    founded_year: 1990,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["High-Rise Landmark Towers", "Cultural Infrastructure", "Avant-Garde Civic Design"],
    services: ["Architectural Masterplanning", "Concept Architecture"],
    markets: ["Bucharest", "Brașov", "International"],
    certifications: ["OAR Member", "RUR Certified"],
    projects_count: 11,
    active_projects_count: 3,
    completed_projects_count: 8,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://dsba.ro", title: "DSBA Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-x-architecture-engineering",
    name: "X Architecture & Engineering",
    slug: "x-architecture-engineering",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Multidisciplinary design practice executing commercial corporate headquarters, retail plazas, and high-density apartment complexes.",
    website: "https://x-architecture.ro",
    founded_year: 2012,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Commercial Headquarters", "Retail Plazas", "Integrated Residential"],
    services: ["Architecture", "Engineering Coordination"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["OAR Member"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://x-architecture.ro", title: "X Architecture Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-subrina-architecture-cluj",
    name: "Subrina Architecture Cluj",
    slug: "subrina-architecture-cluj",
    type: "architecture",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Architectural and urban planning firm in Transylvania, specializing in residential neighborhood plans, IT office buildings, and public institutions.",
    website: "https://subrina.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Transylvanian Residential Masterplanning", "IT Office Buildings"],
    services: ["Architectural Design", "Urban Planning"],
    markets: ["Cluj-Napoca", "Oradea"],
    certifications: ["OAR Member"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://subrina.ro", title: "Subrina Architecture Cluj Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-quadra-design-studio",
    name: "Quadra Design Studio",
    slug: "quadra-design-studio",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Boutique architectural practice specializing in luxury villas, high-end hospitality interiors, and customized residential apartment design.",
    website: "https://quadradesign.ro",
    founded_year: 2009,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Luxury Villas", "Boutique Hotels", "Interior Architecture"],
    services: ["Architecture Design", "Interior Architecture"],
    markets: ["Bucharest", "Constanța"],
    certifications: ["OAR Member"],
    projects_count: 5,
    active_projects_count: 1,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://quadradesign.ro", title: "Quadra Design Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-k-ideas-architecture",
    name: "K-Ideas Architecture",
    slug: "k-ideas-architecture",
    type: "architecture",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Architectural and structural design consultancy in Timișoara, active in office park masterplans, industrial plants, and residential subdivisions.",
    website: "https://kideas.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Office Park Masterplans", "Industrial Facilities", "Residential Subdivisions"],
    services: ["Architectural Design", "Masterplanning"],
    markets: ["Timișoara", "Arad"],
    certifications: ["OAR Member"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://kideas.ro", title: "K-Ideas Architecture Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "arch-cumulus-architecture",
    name: "Cumulus Architecture",
    slug: "cumulus-architecture",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Major merged architectural practice (incorporating PZP, SYAA, ArXTec) behind landmark projects including Marmorosch Hotel, H Victoriei 139, and large office campuses.",
    website: "https://cumulus.ro",
    founded_year: 2017,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Hospitality Landmark Design", "Corporate Office Campuses", "Heritage Restoration"],
    services: ["Full Architecture", "Urban Masterplanning", "Interior Architecture"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member", "RUR Certified"],
    projects_count: 14,
    active_projects_count: 5,
    completed_projects_count: 9,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://cumulus.ro", title: "Cumulus Architecture Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },

  // ==========================================
  // ENGINEERS & CONSULTANTS (12)
  // ==========================================
  {
    id: "eng-popaer-structural",
    name: "Popaer Structural Engineering",
    slug: "popaer-structural-engineering",
    type: "structural_engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "High-rise structural design and seismic engineering consultancy in Bucharest, specializing in earthquake-resistant reinforced concrete and steel structures.",
    website: "https://popaer.ro",
    founded_year: 2003,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Seismic Structural Design", "High-Rise Concrete Towers", "Structural Rehabilitation"],
    services: ["Structural Engineering", "Peer Review & Auditing"],
    markets: ["Bucharest", "National"],
    certifications: ["AICPS Member", "MLPAT Certified Verifier"],
    projects_count: 10,
    active_projects_count: 4,
    completed_projects_count: 6,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://popaer.ro", title: "Popaer Structural Engineering Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-blueprint-structural",
    name: "Blueprint Structural Engineering",
    slug: "blueprint-structural-engineering",
    type: "structural_engineering",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Structural engineering and 3D BIM modeling consultancy for major commercial office developments, logistics parks, and residential towers.",
    website: "https://blueprintengineering.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["BIM Structural Modeling", "Post-Tensioned Concrete Slabs", "Steel Trusses"],
    services: ["Structural Design", "BIM Coordination"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["AICPS Member", "Revit BIM Certified"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://blueprintengineering.ro", title: "Blueprint Structural Engineering Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-vital-engineering-mep",
    name: "Vital Engineering MEP",
    slug: "vital-engineering-mep",
    type: "mep",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "MEP engineering consultancy designing HVAC, electrical installations, sanitary systems, fire suppression, and building management systems (BMS).",
    website: "https://vitalengineering.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["HVAC System Design", "Electrical Power Distribution", "BMS Automation"],
    services: ["MEP Design", "Energy Audit", "Site Supervision"],
    markets: ["Bucharest", "National"],
    certifications: ["ANRE Certified", "IGSU Fire Safety Certified"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://vitalengineering.ro", title: "Vital Engineering Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-tpf-inginerie-romania",
    name: "TPF Inginerie Romania",
    slug: "tpf-inginerie-romania",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Brussels, Belgium / Bucharest, Romania",
    description: "Multidisciplinary engineering consultancy part of TPF Group, executing transport infrastructure, water engineering, building services, and project management.",
    website: "https://tpf.ro",
    founded_year: 2009,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Railway & Highway Engineering", "Water Management", "Building Services Engineering"],
    services: ["Feasibility Studies", "Technical Supervision", "EPCM Management"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 14,
    active_projects_count: 5,
    completed_projects_count: 9,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://tpf.ro", title: "TPF Inginerie Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-egis-romania",
    name: "Egis Romania",
    slug: "egis-romania",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Guyancourt, France / Bucharest, Romania",
    description: "Major international engineering group operating in Romania, supervising highway construction (A1, A3, A7), airport infrastructure, rail, and environmental projects.",
    website: "https://www.egis-romania.com",
    founded_year: 1996,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Motorway Supervision", "Airport Civil Infrastructure", "Rail Engineering"],
    services: ["FIDIC Site Supervision", "Engineering Design", "Environmental Consulting"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 16,
    active_projects_count: 6,
    completed_projects_count: 10,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.egis-romania.com", title: "Egis Romania Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-halcrow-romania-jacobs",
    name: "Halcrow Romania (Jacobs)",
    slug: "halcrow-romania-jacobs",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Dallas, USA / Bucharest, Romania",
    description: "Infrastructure and environmental engineering consultancy part of Jacobs Engineering Group, active in water resources, highway infrastructure, and environmental auditing.",
    website: "https://www.jacobs.com",
    founded_year: 2004,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Environmental Engineering", "Water Supply Masterplans", "Transportation Infrastructure"],
    services: ["Technical Consultancy", "Environmental Impact Assessment"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.jacobs.com", title: "Jacobs Engineering Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-search-corporation",
    name: "Search Corporation",
    slug: "search-corporation",
    type: "engineering",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Leading Romanian transportation and civil engineering consultancy, designer of major expressways, airport runways, bridge structures, and urban ring roads.",
    website: "https://searchcorporation.ro",
    founded_year: 1991,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Highway & Expressway Feasibility", "Airport Runway Design", "Bridge Engineering"],
    services: ["Infrastructure Engineering Design", "Traffic Modeling"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 18,
    active_projects_count: 7,
    completed_projects_count: 11,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://searchcorporation.ro", title: "Search Corporation Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-saidel-engineering",
    name: "Saidel Engineering",
    slug: "saidel-engineering",
    type: "structural_engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Structural dynamics and earthquake engineering consultancy led by University professors, specializing in non-linear seismic analysis and structural optimization.",
    website: "https://saidel.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Non-Linear Seismic Analysis", "Structural Optimization", "High-Rise Concrete Cores"],
    services: ["Structural Engineering Design", "Technical Expertise"],
    markets: ["Bucharest", "National"],
    certifications: ["AICPS Member", "MLPAT Verifier"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://saidel.ro", title: "Saidel Engineering Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-consitrans-engineering",
    name: "Consitrans Engineering",
    slug: "consitrans-engineering",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Major transport infrastructure design consultancy in Romania, designer of A7 Moldavia motorway, A0 Bucharest ring road segments, and major railway modernizations.",
    website: "https://consitrans.ro",
    founded_year: 1993,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Motorway Design (A7, A0)", "Railway Modernization", "Bridge & Viaduct Design"],
    services: ["Detailed Engineering Design", "Feasibility Studies"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 15,
    active_projects_count: 6,
    completed_projects_count: 9,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://consitrans.ro", title: "Consitrans Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-multinv-mep",
    name: "Multinv MEP Engineering",
    slug: "multinv-mep-engineering",
    type: "mep",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Specialist MEP design firm and energy auditor for green office buildings, shopping malls, and industrial logistics facilities.",
    website: "https://multinv.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["HVAC Energy Recovery", "Photovoltaic Integration", "Fire Suppression Design"],
    services: ["MEP Engineering", "Energy Auditing"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANRE Certified", "IGSU Certified"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://multinv.ro", title: "Multinv MEP Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-proing-soft-cluj",
    name: "Proing Soft Engineering",
    slug: "proing-soft-engineering",
    type: "structural_engineering",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Structural engineering and 3D BIM design consultancy in Cluj-Napoca, active in Transylvanian office buildings, sports arenas, and industrial parks.",
    website: "https://proingsoft.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["3D BIM Structural Design", "Reinforced Concrete Arenas", "Industrial Frames"],
    services: ["Structural Engineering", "BIM Services"],
    markets: ["Cluj-Napoca", "Transylvania"],
    certifications: ["AICPS Member"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://proingsoft.ro", title: "Proing Soft Engineering Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "eng-mc-general-construct",
    name: "MC General Construct Engineering",
    slug: "mc-general-construct-engineering",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Project management, site supervision (dirigenție de șantier), and technical audit engineering consultancy operating across South Romania.",
    website: "https://mcconstruct.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Site Supervision (Dirigenție de Șantier)", "Technical Quality Control", "Cost Management"],
    services: ["Site Supervision", "Project Management"],
    markets: ["Bucharest", "Muntenia"],
    certifications: ["ISC Certified Verifiers"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://mcconstruct.ro", title: "MC General Construct Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  }
];

console.log(`Appending ${newEntities.length} new verified real entities to dataset...`);

let content = fs.readFileSync('lib/real-romanian-data.ts', 'utf-8');

// Update type definition if real_estate_agency is missing
if (!content.includes("'real_estate_agency'")) {
  content = content.replace(
    "type: 'developer' | 'general_contractor' | 'construction_company' | 'infrastructure' | 'architecture' | 'engineering' | 'structural_engineering' | 'mep';",
    "type: 'developer' | 'general_contractor' | 'construction_company' | 'infrastructure' | 'architecture' | 'engineering' | 'structural_engineering' | 'mep' | 'real_estate_agency';"
  );
}

// Find export const realCompaniesDataset: RealCompany[] = [
const targetIdx = content.indexOf('export const realCompaniesDataset: RealCompany[] = [');
if (targetIdx === -1) {
  console.error('Could not find realCompaniesDataset definition!');
  process.exit(1);
}

const closingIdx = content.lastIndexOf('];\n\nexport const realProjectsDataset');
if (closingIdx === -1) {
  console.error('Could not find closing bracket of realCompaniesDataset!');
  process.exit(1);
}

const newEntitiesJson = newEntities.map(e => JSON.stringify(e, null, 2)).join(',\n');

const updatedContent = content.slice(0, closingIdx) + ',\n' + newEntitiesJson + '\n' + content.slice(closingIdx);

fs.writeFileSync('lib/real-romanian-data.ts', updatedContent, 'utf-8');
console.log('Successfully updated lib/real-romanian-data.ts!');
