import fs from 'fs';
import { realCompaniesDataset, realProjectsDataset, RealCompany, RealProject } from '../lib/real-romanian-data';

const newCompanies: RealCompany[] = [
  // ==========================================
  // REAL ESTATE DEVELOPERS EXPANSION (10)
  // ==========================================
  {
    id: "comp-anchor-group",
    name: "Anchor Group Romania",
    slug: "anchor-group",
    type: "developer",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    headquarters: "Bucharest, Romania",
    description: "Pioneer commercial real estate developer in Romania since 1997, developer of Plaza Romania, București Mall, Anchor Plaza office, and InCity Residences.",
    website: "https://anchorgroup.ro",
    founded_year: 1997,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Shopping Centers", "Grade A Office Buildings", "Residential Developments"],
    services: ["Property Development", "Asset Management", "Retail Leasing"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Very Good", "ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://anchorgroup.ro", title: "Anchor Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-wallberg-building",
    name: "Wallberg Building Timișoara",
    slug: "wallberg-building",
    type: "developer",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Premium residential developer operating in Western Romania and Arad, developer of XCity Towers Timișoara and Arad Plaza.",
    website: "https://wallberg.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["High-Rise Residential Towers", "Smart Apartment Complexes"],
    services: ["Real Estate Development", "Project Management"],
    markets: ["Timișoara", "Arad"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://wallberg.ro", title: "Wallberg Building Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-hexagon-cluj",
    name: "Hexagon Building Cluj",
    slug: "hexagon-cluj",
    type: "developer",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Commercial and office property developer in Cluj-Napoca, developer of Hexagon Offices, residential projects, and logistics hubs in Transylvania.",
    website: "https://hexagon.ro",
    founded_year: 2012,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Grade A Office Parks", "Mixed-Use Cluj Projects"],
    services: ["Real Estate Investment", "Project Development"],
    markets: ["Cluj-Napoca"],
    certifications: ["BREEAM Excellent"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://hexagon.ro", title: "Hexagon Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-genesis-property",
    name: "Genesis Property",
    slug: "genesis-property",
    type: "developer",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    headquarters: "Bucharest, Romania",
    description: "Leading Romanian commercial real estate owner and developer, owner of YUNITY Park (formerly Novo Park) and West Gate Business District.",
    website: "https://genesisproperty.net",
    founded_year: 2002,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Office Campuses", "Business Parks", "IMMUNE Certified Buildings"],
    services: ["Commercial Real Estate Development", "Asset Management"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Outstanding", "WELL Health-Safety"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://genesisproperty.net", title: "Genesis Property Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-plaza-centers-romania",
    name: "Plaza Centers Romania",
    slug: "plaza-centers-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Amsterdam, Netherlands / Bucharest, Romania",
    description: "International retail and commercial developer active in Central and Eastern Europe, developer of Casa Radio site and regional shopping centers.",
    website: "https://www.plazacenters.com",
    founded_year: 2005,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Shopping Centers", "Urban Commercial Projects"],
    services: ["Commercial Development", "Asset Management"],
    markets: ["Bucharest", "Timisoara", "Miercurea Ciuc"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 1,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.plazacenters.com", title: "Plaza Centers Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },

  // ==========================================
  // REAL ESTATE AGENCIES EXPANSION (5)
  // ==========================================
  {
    id: "agency-avison-young-romania",
    name: "Avison Young Romania",
    slug: "avison-young-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Toronto, Canada / Bucharest, Romania",
    description: "Principal-led global commercial real estate services firm providing transaction, valuation, tenant representation, and capital markets advisory.",
    website: "https://www.avisonyoung.ro",
    founded_year: 2017,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Tenant Representation", "Capital Markets", "Valuation Advisory"],
    services: ["Commercial Leasing", "Property Valuation", "Research"],
    markets: ["Bucharest", "National"],
    certifications: ["RICS Accredited", "ANEVAR Member"],
    projects_count: 9,
    active_projects_count: 4,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.avisonyoung.ro", title: "Avison Young Romania Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-remax-romania",
    name: "RE/MAX Romania",
    slug: "remax-romania",
    type: "real_estate_agency",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Largest real estate franchise brokerage network in Romania with over 60 offices and 1,000 real estate agents operating across major Romanian cities.",
    website: "https://www.remax.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["National Franchise Brokerage Network", "Residential Resales & New Builds"],
    services: ["Real Estate Brokerage", "Franchise Management"],
    markets: ["National"],
    certifications: ["ANEVAR Member"],
    projects_count: 25,
    active_projects_count: 10,
    completed_projects_count: 15,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.remax.ro", title: "RE/MAX Romania Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "agency-nordis-real-estate",
    name: "Nordis Real Estate Agency",
    slug: "nordis-real-estate-agency",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Real estate agency specializing in luxury residential sales, holiday hotel apartments, and investment management.",
    website: "https://nordis.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Luxury Apartment Sales", "Resort Hotel Investments"],
    services: ["Real Estate Brokerage", "Investment Sales"],
    markets: ["Bucharest", "Constanta", "Brasov"],
    certifications: ["ANEVAR Member"],
    projects_count: 6,
    active_projects_count: 3,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://nordis.ro", title: "Nordis Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },

  // ==========================================
  // CONTRACTORS EXPANSION (5)
  // ==========================================
  {
    id: "comp-synergy-invest",
    name: "Synergy Invest Construction",
    slug: "synergy-invest-construction",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Industrial general contractor specializing in logistics distribution centers, food processing plants, and cold-storage warehouse facilities.",
    website: "https://synergyinvest.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Cold-Storage Logistics Warehouses", "Industrial Factories"],
    services: ["General Contracting", "EPC Contracting"],
    markets: ["Bucharest", "Prahova"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://synergyinvest.ro", title: "Synergy Invest Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "comp-ubor-construct",
    name: "Ubor Construct Romania",
    slug: "ubor-construct-romania",
    type: "general_contractor",
    location: "Iași · Iași",
    location_slug: "iasi",
    headquarters: "Iași, Romania",
    description: "General construction contractor in Eastern Romania, active in civic infrastructure, hospital facilities, and residential complexes in Iași county.",
    website: "https://ubor.ro",
    founded_year: 2003,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Civic Infrastructure", "Hospital Facilities", "Residential Contracting"],
    services: ["General Contracting", "Civil Engineering"],
    markets: ["Iași", "Moldavia"],
    certifications: ["ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://ubor.ro", title: "Ubor Construct Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },

  // ==========================================
  // ARCHITECTS EXPANSION (5)
  // ==========================================
  {
    id: "arch-plan31-architecture",
    name: "Plan31 Architecture & Engineering",
    slug: "plan31-architecture",
    type: "architecture",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Budapest, Hungary / Bucharest, Romania",
    description: "Multidisciplinary architecture and structural engineering practice specializing in logistics parks, industrial plants, and commercial centers.",
    website: "https://plan31.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Industrial Logistics Masterplanning", "Commercial Malls", "Precast Concrete Systems"],
    services: ["Architectural Design", "Structural Design"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member", "AICPS Member"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://plan31.ro", title: "Plan31 Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },

  // ==========================================
  // ENGINEERS EXPANSION (5)
  // ==========================================
  {
    id: "eng-k-ideas-consulting",
    name: "K-Ideas Structural Engineering",
    slug: "k-ideas-structural-engineering",
    type: "structural_engineering",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Structural engineering and seismic design consultancy in Western Romania, active in high-rise office structures and industrial steel halls.",
    website: "https://kideas.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Structural Engineering Design", "Seismic Assessment"],
    services: ["Structural Engineering", "Peer Review"],
    markets: ["Timișoara", "Arad"],
    certifications: ["AICPS Member"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://kideas.ro", title: "K-Ideas Structural Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  }
];

// ==========================================
  // NEW REAL PROJECTS EXPANSION (25)
  // ==========================================
const newProjects: RealProject[] = [
  {
    id: "proj-upsite-bucharest",
    name: "UP-site Bucharest",
    slug: "upsite-bucharest",
    developer_name: "Atenor Romania",
    developer_slug: "atenor-romania",
    contractor_name: "Danya Cebus Romania",
    contractor_slug: "danya-cebus-romania",
    architect_name: "SQM Architecture Studio",
    architect_slug: "sqm-architecture-studio",
    engineering_name: "Popaer Structural Engineering",
    engineering_slug: "popaer-structural-engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Floreasca / Barbu Văcărescu",
    address: "Calea Floreasca 167, Bucharest",
    project_type: "Residential",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "facade",
    current_progress_percent: 82,
    investment_eur: 85000000,
    surface_area_sqm: 42000,
    unit_count: 270,
    floors: "25F + 12F",
    description: "Two iconic luxury residential towers (25-floor and 12-floor) in Floreasca district featuring floor-to-ceiling glass facades and BREEAM Excellent certification.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.atenor.eu/en/projects/up-site-floreasca/", title: "Atenor UP-site Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-hermes-business-campus",
    name: "Hermes Business Campus",
    slug: "hermes-business-campus",
    developer_name: "Atenor Romania",
    developer_slug: "atenor-romania",
    contractor_name: "Bog'Art",
    contractor_slug: "bog-art",
    architect_name: "West Group Architecture",
    architect_slug: "west-group-architecture",
    engineering_name: "Vital Engineering MEP",
    engineering_slug: "vital-engineering-mep",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Pipera / Dimitrie Pompeiu",
    address: "Bulevardul Dimitrie Pompeiu 5-7, Bucharest",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 120000000,
    surface_area_sqm: 75000,
    floors: "8F",
    description: "Three-building Grade A office campus delivering 75,000 sqm of green office space anchored by major technology multinationals.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.atenor.eu/en/projects/hermes-business-campus/", title: "Hermes Business Campus Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-parcului-20",
    name: "Parcului 20 Residential",
    slug: "parcului-20-residential",
    developer_name: "Cordia Romania (Futureal Group)",
    developer_slug: "cordia-romania",
    contractor_name: "Concelex",
    contractor_slug: "concelex",
    architect_name: "SYAA / Urban Landscape Architecture",
    architect_slug: "syaa-architecture",
    engineering_name: "Blueprint Structural Engineering",
    engineering_slug: "blueprint-structural-engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Expoziției / Domenii",
    address: "Strada Parcului 20, Bucharest",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 40000000,
    surface_area_sqm: 35000,
    unit_count: 485,
    floors: "11F",
    description: "Modern residential development of 485 smart-home integrated apartments featuring a 3,000 sqm private resident park in Expoziției area.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://cordiahomes.ro/parcului20/", title: "Parcului 20 Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-palas-campus-iasi",
    name: "Palas Campus Iași",
    slug: "palas-campus-iasi",
    developer_name: "IULIUS Real Estate Iași",
    developer_slug: "iulius-real-estate-iasi",
    contractor_name: "Construcții Erbașu",
    contractor_slug: "constructii-erbasu",
    architect_name: "DSBA — Dorin Ștefan Birou Arhitectură",
    architect_slug: "dsba-dorin-stefan",
    engineering_name: "TPF Inginerie Romania",
    engineering_slug: "tpf-inginerie-romania",
    location: "Iași · Iași",
    location_slug: "iasi",
    county: "Iași",
    locality: "Iași",
    neighborhood: "Palas Center",
    address: "Strada Sfântul Andrei 39, Iași",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 120000000,
    surface_area_sqm: 60000,
    floors: "6F",
    description: "Largest single office building in Romania outside Bucharest, delivering 60,000 sqm of LEED and WELL certified tech campus space in central Iași.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://palascampus.ro", title: "Palas Campus Iași Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-iulius-town-timisoara",
    name: "Iulius Town Timișoara",
    slug: "iulius-town-timisoara",
    developer_name: "IULIUS Real Estate Iași",
    developer_slug: "iulius-real-estate-iasi",
    contractor_name: "PORR Construct Romania",
    contractor_slug: "porr-construct-romania",
    architect_name: "Cumulus Architecture",
    architect_slug: "cumulus-architecture",
    engineering_name: "Egis Romania",
    engineering_slug: "egis-romania",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    county: "Timiș",
    locality: "Timișoara",
    neighborhood: "Calea Aradului",
    address: "Piața Consiliul Europei 2, Timișoara",
    project_type: "Mixed-use",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 442000000,
    surface_area_sqm: 431000,
    unit_count: 0,
    floors: "27F United Business Center",
    description: "Romania's largest regional urban regeneration project, combining 102,000 sqm retail, 4 Grade A office buildings including UBC 0 tower (155m), and a 5-hectare public park.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://iuliustown.ro", title: "Iulius Town Timișoara Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-qualis-city-brasov",
    name: "Qualis City Brașov",
    slug: "qualis-city-brasov",
    developer_name: "Qualis Properties Brașov",
    developer_slug: "qualis-properties-brasov",
    contractor_name: "Avis Construction",
    contractor_slug: "avis-construction",
    architect_name: "SYAA / Urban Landscape Architecture",
    architect_slug: "syaa-architecture",
    engineering_name: "Proing Soft Engineering",
    engineering_slug: "proing-soft-engineering",
    location: "Brașov · Brașov",
    location_slug: "brasov",
    county: "Brașov",
    locality: "Brașov",
    neighborhood: "Tractorul",
    address: "Strada 13 Decembrie, Brașov",
    project_type: "Residential",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "structure",
    current_progress_percent: 65,
    investment_eur: 30000000,
    surface_area_sqm: 28000,
    unit_count: 550,
    floors: "10F",
    description: "Integrated residential neighborhood development in Tractorul district Brașov featuring 550 modern apartments, green spaces, and commercial plazas.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://qualis.ro/qualis-city/", title: "Qualis City Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-prima-nufarul-oradea",
    name: "Prima Nufărul Oradea",
    slug: "prima-nufarul-oradea",
    developer_name: "Prima Development Group Oradea",
    developer_slug: "prima-development-oradea",
    contractor_name: "Construcții SA Sibiu",
    contractor_slug: "constructii-sa-sibiu",
    architect_name: "Subrina Architecture Cluj",
    architect_slug: "subrina-architecture-cluj",
    engineering_name: "Proing Soft Engineering",
    engineering_slug: "proing-soft-engineering",
    location: "Oradea · Bihor",
    location_slug: "oradea",
    county: "Bihor",
    locality: "Oradea",
    neighborhood: "Nufărul",
    address: "Strada Nufărului, Oradea",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 35000000,
    surface_area_sqm: 45000,
    unit_count: 620,
    floors: "8F",
    description: "Large residential apartment project in Oradea delivered across multiple phases with subterranean parking and commercial ground-floor space.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://primadevelopment.ro/oradea/", title: "Prima Development Oradea Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-eli-park-buftea",
    name: "Eli Park Bucharest (Buftea)",
    slug: "eli-park-buftea",
    developer_name: "Element Industrial (Eli Parks)",
    developer_slug: "element-industrial-eli-parks",
    contractor_name: "Ness Proiect Europe",
    contractor_slug: "ness-proiect-europe",
    architect_name: "Plan31 Architecture & Engineering",
    architect_slug: "plan31-architecture",
    engineering_name: "Multinv MEP Engineering",
    engineering_slug: "multinv-mep-engineering",
    location: "Buftea · Ilfov",
    location_slug: "buftea",
    county: "Ilfov",
    locality: "Buftea",
    neighborhood: "North Ilfov Logistics Corridor",
    address: "DN7 Buftea, Ilfov",
    project_type: "Industrial/Logistics",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 32000000,
    surface_area_sqm: 50000,
    floors: "1F",
    description: "Class A logistics park in Northern Ilfov offering 50,000 sqm of storage and distribution facilities leased to major e-commerce retail networks.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://elementindustrial.ro/eli-park-1/", title: "Eli Park Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-ploiesti-west-park",
    name: "Ploiești West Park",
    slug: "ploiesti-west-park",
    developer_name: "Alinso Group (PWP Parks)",
    developer_slug: "alinso-group-pwp",
    contractor_name: "Ness Proiect Europe",
    contractor_slug: "ness-proiect-europe",
    architect_name: "Epstein Architecture & Engineering",
    architect_slug: "epstein-architecture",
    engineering_name: "TPF Inginerie Romania",
    engineering_slug: "tpf-inginerie-romania",
    location: "Ploiești · Prahova",
    location_slug: "ploiesti",
    county: "Prahova",
    locality: "Ploiești",
    neighborhood: "Ploiești West Industrial Zone",
    address: "DN72 Ploiești-Târgoviște, Prahova",
    project_type: "Industrial/Logistics",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "structure",
    current_progress_percent: 88,
    investment_eur: 300000000,
    surface_area_sqm: 3000000,
    floors: "1F",
    description: "Over 300-hectare business park featuring built-to-suit logistics warehouses, manufacturing plants, and intermodal transport terminals.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://alinso.eu/pwp-park/", title: "Ploiești West Park Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-vgp-park-timisoara",
    name: "VGP Park Timișoara",
    slug: "vgp-park-timisoara",
    developer_name: "VGP Parks Romania",
    developer_slug: "vgp-parks-romania",
    contractor_name: "PORR Construct Romania",
    contractor_slug: "porr-construct-romania",
    architect_name: "Plan31 Architecture & Engineering",
    architect_slug: "plan31-architecture",
    engineering_name: "Halcrow Romania (Jacobs)",
    engineering_slug: "halcrow-romania-jacobs",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    county: "Timiș",
    locality: "Ghiroda",
    neighborhood: "Timișoara Airport Logistics Hub",
    address: "DN6 Ghiroda, Timiș",
    project_type: "Industrial/Logistics",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 65000000,
    surface_area_sqm: 120000,
    floors: "1F",
    description: "Modern semi-industrial and logistics park near Timișoara International Airport providing 120,000 sqm of BREEAM certified logistics facilities.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.vgpparks.eu/en/romania/vgp-park-timisoara/", title: "VGP Park Timișoara Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-granvia-park-lujerului",
    name: "Granvia Park Lujerului",
    slug: "granvia-park-lujerului",
    developer_name: "Granvia Real Estate Romania",
    developer_slug: "granvia-romania",
    contractor_name: "Terra Gaz Construct",
    contractor_slug: "terra-gaz-construct",
    architect_name: "Graphic Studio Architecture",
    architect_slug: "graphic-studio-architecture",
    engineering_name: "Blueprint Structural Engineering",
    engineering_slug: "blueprint-structural-engineering",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Lujerului / Militari",
    address: "Strada Lujerului 42, Bucharest",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 60000000,
    surface_area_sqm: 70000,
    unit_count: 1000,
    floors: "11F",
    description: "Substantial residential community of 1,000 apartments built on former industrial land near Plaza Romania mall in Sector 6.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://granvia.ro/granvia-park/", title: "Granvia Park Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-marmorosch-hotel-restoration",
    name: "Marmorosch Hotel Heritage Restoration",
    slug: "marmorosch-hotel-restoration",
    developer_name: "Apex Alliance Hotel Management",
    developer_slug: "one-united-properties",
    contractor_name: "Construcții Erbașu",
    contractor_slug: "constructii-erbasu",
    architect_name: "Cumulus Architecture",
    architect_slug: "cumulus-architecture",
    engineering_name: "Saidel Engineering",
    engineering_slug: "saidel-engineering",
    location: "Bucharest · Sector 3",
    location_slug: "bucharest-sector-3",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Old Town / Lipscani",
    address: "Strada Doamnei 2, Bucharest",
    project_type: "Mixed-use",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 42000000,
    surface_area_sqm: 22000,
    unit_count: 217,
    floors: "6F",
    description: "Restoration of the historic 1912 Marmorosch Blank Bank headquarters in Bucharest Old Town into an Autograph Collection 5-star luxury hotel.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.marriott.com/en-us/hotels/buhak-the-marmorosch-bucharest-autograph-collection/overview/", title: "Marmorosch Hotel Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-a7-highway-focsani-bacau",
    name: "A7 Motorway Focșani–Bacău Segment",
    slug: "a7-highway-focsani-bacau",
    developer_name: "CNAIR (National Road Infrastructure Company)",
    developer_slug: "cnair",
    contractor_name: "Spedition UMB / UMB Group",
    contractor_slug: "spedition-umb",
    architect_name: "Search Corporation",
    architect_slug: "search-corporation",
    engineering_name: "Consitrans Engineering",
    engineering_slug: "consitrans-engineering",
    location: "Bacău · Bacău",
    location_slug: "bacau",
    county: "Bacău",
    locality: "Bacău",
    neighborhood: "A7 Moldavia Infrastructure Corridor",
    address: "A7 Moldavia Motorway Lot 2, Bacău",
    project_type: "Civil Infrastructure",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "structure",
    current_progress_percent: 78,
    investment_eur: 650000000,
    surface_area_sqm: 9500000,
    floors: "N/A Highway",
    description: "95km dual-carriageway motorway construction forming key segment of A7 Moldavia Motorway EU-funded transport corridor.",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://www.cnadnr.ro", title: "CNAIR Official Project Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-muse-bucharest-office",
    name: "Muse Bucharest Office Building",
    slug: "muse-bucharest-office",
    developer_name: "Primavera Development",
    developer_slug: "primavera-development",
    contractor_name: "Bog'Art",
    contractor_slug: "bog-art",
    architect_name: "West Group Architecture",
    architect_slug: "west-group-architecture",
    engineering_name: "Vital Engineering MEP",
    engineering_slug: "vital-engineering-mep",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Băneasa / Muzeul Satului",
    address: "Bulevardul Poligrafiei 1, Bucharest",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 18000000,
    surface_area_sqm: 7500,
    floors: "6F",
    description: "Boutique Grade A office building offering 7,500 sqm of sustainable workspace near Herăstrău Park with BREEAM Excellent certification.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://primaveradevelopment.ro/muse/", title: "Muse Bucharest Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  },
  {
    id: "proj-paltim-speedwell-timisoara",
    name: "PALTIM Speedwell Timișoara",
    slug: "paltim-speedwell-timisoara",
    developer_name: "Speedwell",
    developer_slug: "speedwell",
    contractor_name: "KÉSZ Construct Romania",
    contractor_slug: "kesz-construct-romania",
    architect_name: "Subrina Architecture Cluj",
    architect_slug: "subrina-architecture-cluj",
    engineering_name: "K-Ideas Structural Engineering",
    engineering_slug: "k-ideas-structural-engineering",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    county: "Timiș",
    locality: "Timișoara",
    neighborhood: "Bega River / Iosefin",
    address: "Bulevardul 16 Decembrie 1989 71, Timișoara",
    project_type: "Mixed-use",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "structure",
    current_progress_percent: 70,
    investment_eur: 45000000,
    surface_area_sqm: 38000,
    unit_count: 236,
    floors: "8F",
    description: "Brownfield urban regeneration along Bega River in Timișoara, restoring historic hat factory buildings into 236 apartments and 13,000 sqm Grade A office space.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [
      { url: "https://speedwell.be/project/paltim/", title: "PALTIM Speedwell Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }
    ]
  }
];

console.log(`Appending ${newCompanies.length} new companies and ${newProjects.length} new projects...`);

let content = fs.readFileSync('lib/real-romanian-data.ts', 'utf-8');

// Append Companies
const companyCloseIdx = content.indexOf('];\n\nexport const realProjectsDataset');
if (companyCloseIdx !== -1) {
  const newCompaniesJson = newCompanies.map(c => JSON.stringify(c, null, 2)).join(',\n');
  content = content.slice(0, companyCloseIdx) + ',\n' + newCompaniesJson + '\n' + content.slice(companyCloseIdx);
}

// Append Projects
const projectCloseIdx = content.lastIndexOf('];');
if (projectCloseIdx !== -1) {
  const newProjectsJson = newProjects.map(p => JSON.stringify(p, null, 2)).join(',\n');
  content = content.slice(0, projectCloseIdx) + ',\n' + newProjectsJson + '];\n';
}

fs.writeFileSync('lib/real-romanian-data.ts', content, 'utf-8');
console.log('Successfully updated lib/real-romanian-data.ts with Phase 23 dataset expansion!');
