import fs from 'fs';
import { RealCompany, RealProject } from '../lib/real-romanian-data';

const finalCompanies: RealCompany[] = [
  // ARCHITECTS (4) -> total 21
  {
    id: "arch-bca-urban-studio",
    name: "BCA Urban Studio",
    slug: "bca-urban-studio",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Urban planning and architecture studio specialized in city masterplanning, public plazas, and residential zoning.",
    website: "https://bcaurban.ro",
    founded_year: 2011,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["City Zoning", "Urban Masterplanning"],
    services: ["Urban Architecture"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["OAR Member", "RUR Member"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://bcaurban.ro", title: "BCA Urban Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-arteks-design",
    name: "Arteks Architecture Design",
    slug: "arteks-architecture-design",
    type: "architecture",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Architectural office in Timișoara designing commercial centers, residential complexes, and restored heritage monuments.",
    website: "https://arteks.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Timișoara Heritage Restorations", "Commercial Architecture"],
    services: ["Architectural Design"],
    markets: ["Timișoara", "Arad"],
    certifications: ["OAR Member"],
    projects_count: 8,
    active_projects_count: 2,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://arteks.ro", title: "Arteks Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-pro-concept-iasi",
    name: "Pro Concept Architecture Iași",
    slug: "pro-concept-architecture-iasi",
    type: "architecture",
    location: "Iași · Iași",
    location_slug: "iasi",
    headquarters: "Iași, Romania",
    description: "Architecture and masterplanning practice serving Eastern Romania, active in educational campuses and residential developments in Iași.",
    website: "https://proconceptiasi.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Iași Residential Architecture", "Campus Masterplanning"],
    services: ["Architectural Services"],
    markets: ["Iași", "Moldavia"],
    certifications: ["OAR Member"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://proconceptiasi.ro", title: "Pro Concept Iași Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-art-grup-brasov",
    name: "Art Grup Architecture Brașov",
    slug: "art-grup-architecture-brasov",
    type: "architecture",
    location: "Brașov · Brașov",
    location_slug: "brasov",
    headquarters: "Brașov, Romania",
    description: "Architecture office in Brașov designing mountain resort chalets, residential parks, and commercial centers.",
    website: "https://artgrupbrasov.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Mountain Hospitality Architecture", "Brașov Housing"],
    services: ["Architectural Design"],
    markets: ["Brașov", "Poiana Brașov"],
    certifications: ["OAR Member"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://artgrupbrasov.ro", title: "Art Grup Brașov Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ENGINEERS (8) -> total 25
  {
    id: "eng-expert-proiect-suceava",
    name: "Expert Proiect Suceava",
    slug: "expert-proiect-suceava",
    type: "engineering",
    location: "Suceava · Suceava",
    location_slug: "iasi",
    headquarters: "Suceava, Romania",
    description: "Civil infrastructure and bridge engineering practice operating in Moldavia and Bukovina.",
    website: "https://expertproiect.ro",
    founded_year: 2002,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Bridge & Road Engineering", "Civic Water Networks"],
    services: ["Infrastructure Engineering"],
    markets: ["Suceava", "Moldavia"],
    certifications: ["ISO 9001"],
    projects_count: 15,
    active_projects_count: 4,
    completed_projects_count: 11,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://expertproiect.ro", title: "Expert Proiect Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-aquaproiect-romania",
    name: "Aquaproiect Romania",
    slug: "aquaproiect-romania",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Hydrotechnical and dam engineering design institute in Romania with over 60 years of history in major water infrastructure.",
    website: "https://aquaproiect.ro",
    founded_year: 1962,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Dam & Hydrotechnical Engineering", "Flood Protection Systems"],
    services: ["Hydrotechnical Engineering"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 50,
    active_projects_count: 10,
    completed_projects_count: 40,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://aquaproiect.ro", title: "Aquaproiect Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-proexrom-iasi",
    name: "Proexrom Engineering Iași",
    slug: "proexrom-engineering-iasi",
    type: "structural_engineering",
    location: "Iași · Iași",
    location_slug: "iasi",
    headquarters: "Iași, Romania",
    description: "Structural engineering design and technical inspection office in Moldavia.",
    website: "https://proexrom.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Seismic Design Iași", "Concrete Structural Design"],
    services: ["Structural Engineering"],
    markets: ["Iași", "Moldavia"],
    certifications: ["AICPS Member"],
    projects_count: 10,
    active_projects_count: 3,
    completed_projects_count: 7,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://proexrom.ro", title: "Proexrom Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-teratest-cluj",
    name: "Teratest Geotehnica Cluj",
    slug: "teratest-geotehnica-cluj",
    type: "engineering",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Geotechnical laboratory and ground investigation engineering firm operating in Transylvania.",
    website: "https://teratestcluj.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Geotechnical Drilling & Soil Testing", "Slope Stability Design"],
    services: ["Geotechnical Engineering"],
    markets: ["Cluj-Napoca", "Transylvania"],
    certifications: ["ISO 9001"],
    projects_count: 20,
    active_projects_count: 6,
    completed_projects_count: 14,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://teratestcluj.ro", title: "Teratest Cluj Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-alistar-security-engineering",
    name: "Alistar Security & Fire Systems",
    slug: "alistar-security-fire-systems",
    type: "mep",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Fire protection and low-voltage electrical engineering design firm for commercial and industrial complexes.",
    website: "https://alistar.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Fire Detection & Sprinkler Systems", "Access Control & CCTV Engineering"],
    services: ["Low-Voltage MEP Engineering"],
    markets: ["Bucharest", "National"],
    certifications: ["IGSU Certified"],
    projects_count: 25,
    active_projects_count: 8,
    completed_projects_count: 17,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://alistar.ro", title: "Alistar Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-utopian-engineering-brasov",
    name: "Utopian MEP Engineering Brașov",
    slug: "utopian-mep-engineering-brasov",
    type: "mep",
    location: "Brașov · Brașov",
    location_slug: "brasov",
    headquarters: "Brașov, Romania",
    description: "HVAC and energy efficiency engineering design firm serving hotel resorts and residential developments in Brașov.",
    website: "https://utopianmep.ro",
    founded_year: 2013,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Heat Pump Systems Design", "nZEB Mechanical Engineering"],
    services: ["MEP Design"],
    markets: ["Brașov"],
    certifications: ["ANRE Certified"],
    projects_count: 11,
    active_projects_count: 3,
    completed_projects_count: 8,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://utopianmep.ro", title: "Utopian MEP Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-geo-proiect-constanta",
    name: "Geo Proiect Constanța",
    slug: "geo-proiect-constanta",
    type: "engineering",
    location: "Constanța · Constanța",
    location_slug: "constanta",
    headquarters: "Constanța, Romania",
    description: "Marine geotechnical and coastal engineering firm designing port facilities and marine breakwaters.",
    website: "https://geoproiect.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Marine Geotechnical Engineering", "Port Quay Design"],
    services: ["Coastal Engineering"],
    markets: ["Constanța", "Mamaia"],
    certifications: ["ISO 9001"],
    projects_count: 14,
    active_projects_count: 4,
    completed_projects_count: 10,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://geoproiect.ro", title: "Geo Proiect Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-stratif-structural-engineering",
    name: "Stratif Structural Engineering",
    slug: "stratif-structural-engineering",
    type: "structural_engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Structural design practice specialized in steel logistics warehouses and precast industrial halls.",
    website: "https://stratif.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Steel Industrial Structure Design", "Precast Concrete Systems"],
    services: ["Structural Engineering"],
    markets: ["Bucharest", "Prahova"],
    certifications: ["AICPS Member"],
    projects_count: 12,
    active_projects_count: 4,
    completed_projects_count: 8,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://stratif.ro", title: "Stratif Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // DEVELOPERS (3) -> total 50
  {
    id: "comp-nordis-group-developer",
    name: "Nordis Group",
    slug: "nordis-group",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Developer of hotel and residential resort complexes in Mamaia, Sinaia, and Bucharest.",
    website: "https://nordis.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Luxury Hotel Resorts", "Black Sea Apartment Hotels"],
    services: ["Real Estate Development", "Hotel Management"],
    markets: ["Constanța", "Brașov", "Bucharest"],
    certifications: ["ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://nordis.ro", title: "Nordis Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-ctp-cluj-development",
    name: "CTPark Cluj",
    slug: "ctpark-cluj",
    type: "developer",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Prague, Czechia / Cluj-Napoca, Romania",
    description: "Industrial logistics park developer member of CTP NV, operator of CTPark Cluj I and II.",
    website: "https://ctp.eu",
    founded_year: 2014,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Class A Cluj Logistics Parks"],
    services: ["Industrial Property Development"],
    markets: ["Cluj-Napoca"],
    certifications: ["BREEAM Very Good"],
    projects_count: 5,
    active_projects_count: 1,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://ctp.eu", title: "CTP Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-speedwell-riverside-arad",
    name: "Speedwell Riverside Arad",
    slug: "speedwell-riverside-arad",
    type: "developer",
    location: "Arad · Arad",
    location_slug: "timisoara",
    headquarters: "Bucharest, Romania",
    description: "Mixed-use urban regeneration project developer on Mureș River in Arad.",
    website: "https://speedwell.be",
    founded_year: 2021,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Arad Urban Regeneration"],
    services: ["Property Development"],
    markets: ["Arad", "Timișoara"],
    certifications: ["BREEAM Excellent"],
    projects_count: 3,
    active_projects_count: 1,
    completed_projects_count: 2,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://speedwell.be", title: "Speedwell Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  }
];

// Final 15 Projects -> total 76
const finalProjects: RealProject[] = [
  {
    id: "proj-nordis-mamaia-resort",
    name: "Nordis Mamaia Hotel & Residence",
    slug: "nordis-mamaia-resort",
    developer_name: "Nordis Group",
    developer_slug: "nordis-group",
    contractor_name: "Construcții Erbașu",
    contractor_slug: "constructii-erbasu",
    architect_name: "X Architecture & Engineering",
    architect_slug: "x-architecture-engineering",
    engineering_name: "Vital Engineering MEP",
    engineering_slug: "vital-engineering-mep",
    location: "Mamaia · Constanța",
    location_slug: "constanta",
    county: "Constanța",
    locality: "Mamaia",
    neighborhood: "Mamaia Nord / Năvodari Beach",
    address: "Bulevardul Mamaia Nord 100, Constanța",
    project_type: "Hospitality",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "facade",
    current_progress_percent: 85,
    investment_eur: 100000000,
    surface_area_sqm: 100000,
    unit_count: 712,
    floors: "11F",
    description: "Luxury 5-star hotel and apartment resort development on Mamaia Nord beach incorporating 712 rooms and apartments, SPA center, and private beach.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://nordis.ro/nordis-mamaia/", title: "Nordis Mamaia Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-ctpark-cluj-logistics",
    name: "CTPark Cluj I Logistics Hub",
    slug: "ctpark-cluj-logistics",
    developer_name: "CTPark Cluj",
    developer_slug: "ctpark-cluj",
    contractor_name: "KÉSZ Construct Romania",
    contractor_slug: "kesz-construct-romania",
    architect_name: "Plan31 Architecture & Engineering",
    architect_slug: "plan31-architecture",
    engineering_name: "Teratest Geotehnica Cluj",
    engineering_slug: "teratest-geotehnica-cluj",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    county: "Cluj",
    locality: "Apahida",
    neighborhood: "Cluj East Airport Logistics Corridor",
    address: "DN1C Apahida, Cluj",
    project_type: "Industrial/Logistics",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 45000000,
    surface_area_sqm: 80000,
    floors: "1F",
    description: "80,000 sqm BREEAM Very Good Class A logistics distribution park near Cluj-Napoca International Airport.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://ctp.eu/properties/romania/ctpark-cluj/", title: "CTPark Cluj Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-speedwell-riverside-arad-site",
    name: "Speedwell Riverside Arad Project",
    slug: "speedwell-riverside-arad-site",
    developer_name: "Speedwell Riverside Arad",
    developer_slug: "speedwell-riverside-arad",
    contractor_name: "KÉSZ Construct Romania",
    contractor_slug: "kesz-construct-romania",
    architect_name: "Subrina Architecture Cluj",
    architect_slug: "subrina-architecture-cluj",
    engineering_name: "K-Ideas Structural Engineering",
    engineering_slug: "k-ideas-structural-engineering",
    location: "Arad · Arad",
    location_slug: "timisoara",
    county: "Arad",
    locality: "Arad",
    neighborhood: "Mureș River Corridor",
    address: "Calea Timișorii 45, Arad",
    project_type: "Mixed-use",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "structure",
    current_progress_percent: 50,
    investment_eur: 40000000,
    surface_area_sqm: 35000,
    unit_count: 200,
    floors: "8F",
    description: "Riverside urban regeneration project in Arad delivering 200 residential units and 10,000 sqm commercial space.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://speedwell.be", title: "Speedwell Arad Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-citadel-residence-craiova",
    name: "Citadel Residence Craiova",
    slug: "citadel-residence-craiova",
    developer_name: "Citadel Development Craiova",
    developer_slug: "citadel-development-craiova",
    contractor_name: "Construcții Erbașu",
    contractor_slug: "constructii-erbasu",
    architect_name: "Pro Concept Architecture Iași",
    architect_slug: "pro-concept-architecture-iasi",
    engineering_name: "Expert Proiect Suceava",
    engineering_slug: "expert-proiect-suceava",
    location: "Craiova · Dolj",
    location_slug: "craiova",
    county: "Dolj",
    locality: "Craiova",
    neighborhood: "Craiovița Nouă",
    address: "Calea Severinului, Craiova",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 28000000,
    surface_area_sqm: 32000,
    unit_count: 420,
    floors: "10F",
    description: "420-apartment modern residential community in Craiova with subterranean parking and landscaped gardens.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://citadelcraiova.ro", title: "Citadel Craiova Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-a1-highway-sibiu-pitesti",
    name: "A1 Motorway Sibiu–Pitești Section 5",
    slug: "a1-highway-sibiu-pitesti",
    developer_name: "CNAIR (National Road Infrastructure Company)",
    developer_slug: "cnair",
    contractor_name: "Webuild / Astaldi Romania",
    contractor_slug: "webuild-romania",
    architect_name: "Search Corporation",
    architect_slug: "search-corporation",
    engineering_name: "Consitrans Engineering",
    engineering_slug: "consitrans-engineering",
    location: "Sibiu · Sibiu",
    location_slug: "sibiu",
    county: "Argeș / Sibiu",
    locality: "Pitești / Curtea de Argeș",
    neighborhood: "A1 Southern Carpathian Trans-Mountain Corridor",
    address: "A1 Motorway Section 5, Curtea de Argeș",
    project_type: "Civil Infrastructure",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "structure",
    current_progress_percent: 72,
    investment_eur: 350000000,
    surface_area_sqm: 3000000,
    floors: "N/A Highway",
    description: "30km motorway section including 12 major bridges and viaducts crossing Trans-Carpathian infrastructure corridor.",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.cnadnr.ro", title: "CNAIR A1 Sibiu-Pitești Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-afi-tech-park-2",
    name: "AFI Tech Park 2 Bucharest",
    slug: "afi-tech-park-2",
    developer_name: "AFI Europe Romania",
    developer_slug: "afi-europe-romania",
    contractor_name: "Danya Cebus Romania",
    contractor_slug: "danya-cebus-romania",
    architect_name: "West Group Architecture",
    architect_slug: "west-group-architecture",
    engineering_name: "Vital Engineering MEP",
    engineering_slug: "vital-engineering-mep",
    location: "Bucharest · Sector 5",
    location_slug: "bucharest-sector-5",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Tudor Vladimirescu / Rahova",
    address: "Bulevardul Tudor Vladimirescu 29, Bucharest",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 37000000,
    surface_area_sqm: 22000,
    floors: "8F",
    description: "Phase 2 of AFI Tech Park office campus delivering 22,000 sqm of LEED Platinum office space in Sector 5.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://afitechipark.ro", title: "AFI Tech Park Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-hils-brauner-residential",
    name: "HILS Brauner Residential",
    slug: "hils-brauner-residential",
    developer_name: "HILS Development",
    developer_slug: "hils-development",
    contractor_name: "Concelex",
    contractor_slug: "concelex",
    architect_name: "Graphic Studio Architecture",
    architect_slug: "graphic-studio-architecture",
    engineering_name: "Popaer Structural Engineering",
    engineering_slug: "popaer-structural-engineering",
    location: "Bucharest · Sector 3",
    location_slug: "bucharest-sector-3",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Pallady East",
    address: "Drumul Gura Crivățului, Bucharest",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 70000000,
    surface_area_sqm: 85000,
    unit_count: 1250,
    floors: "11F",
    description: "Substantial residential development of 1,250 smart apartments across 8 blocks in Sector 3 Pallady corridor.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://hils.ro/hils-brauner/", title: "HILS Brauner Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-sedako-park-timisoara-site",
    name: "Sedako Park Timișoara",
    slug: "sedako-park-timisoara-site",
    developer_name: "Sedako Group Timișoara",
    developer_slug: "sedako-group-timisoara",
    contractor_name: "KÉSZ Construct Romania",
    contractor_slug: "kesz-construct-romania",
    architect_name: "Arteks Architecture Design",
    architect_slug: "arteks-architecture-design",
    engineering_name: "K-Ideas Structural Engineering",
    engineering_slug: "k-ideas-structural-engineering",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    county: "Timiș",
    locality: "Timișoara",
    neighborhood: "Aradului / Lipovei",
    address: "Calea Sever Bocu, Timișoara",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 24000000,
    surface_area_sqm: 26000,
    unit_count: 320,
    floors: "8F",
    description: "320-apartment residential park in Timișoara with commercial plazas and underground parking.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://sedako.ro", title: "Sedako Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-edil-park-cluj-site",
    name: "Edil Park Cluj",
    slug: "edil-park-cluj-site",
    developer_name: "Edil Construcții Cluj",
    developer_slug: "edil-constructii-cluj",
    contractor_name: "Axa Construction",
    contractor_slug: "axa-construction",
    architect_name: "Subrina Architecture Cluj",
    architect_slug: "subrina-architecture-cluj",
    engineering_name: "Proing Soft Engineering",
    engineering_slug: "proing-soft-engineering",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    county: "Cluj",
    locality: "Cluj-Napoca",
    neighborhood: "Mănăștur / Vivo",
    address: "Strada Edilului, Cluj-Napoca",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 30000000,
    surface_area_sqm: 35000,
    unit_count: 450,
    floors: "10F",
    description: "450-apartment residential development in Cluj-Napoca near Vivo Shopping Center.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://edil.ro", title: "Edil Cluj Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-avrig-35-residential",
    name: "Avrig 35 Residential",
    slug: "avrig-35-residential",
    developer_name: "Rock Development Holding",
    developer_slug: "rock-development-holding",
    contractor_name: "Terra Gaz Construct",
    contractor_slug: "terra-gaz-construct",
    architect_name: "Quadra Design Studio",
    architect_slug: "quadra-design-studio",
    engineering_name: "Blueprint Structural Engineering",
    engineering_slug: "blueprint-structural-engineering",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Obor / Bucur Obor",
    address: "Strada Avrig 35, Bucharest",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 20000000,
    surface_area_sqm: 18000,
    unit_count: 210,
    floors: "10F",
    description: "Modern urban residential building in Obor area offering 210 smart apartments and subterranean parking.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://rockdevelopment.ro", title: "Rock Development Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-militari-shopping-expansion",
    name: "Militari Shopping Center Expansion",
    slug: "militari-shopping-expansion",
    developer_name: "Liebrecht & wooD Romania",
    developer_slug: "liebrecht-wood-romania",
    contractor_name: "Ness Proiect Europe",
    contractor_slug: "ness-proiect-europe",
    architect_name: "Epstein Architecture & Engineering",
    architect_slug: "epstein-architecture",
    engineering_name: "Multinv MEP Engineering",
    engineering_slug: "multinv-mep-engineering",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Militari / Iuliu Maniu",
    address: "Bulevardul Iuliu Maniu 546, Bucharest",
    project_type: "Retail",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 35000000,
    surface_area_sqm: 55000,
    floors: "1F",
    description: "55,000 sqm retail park expansion anchored by major international hypermarket and DIY retailers.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://liebrecht-wood.com", title: "Liebrecht & wooD Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-anchor-plaza-office",
    name: "Anchor Plaza Office Tower",
    slug: "anchor-plaza-office",
    developer_name: "Anchor Group Romania",
    developer_slug: "anchor-group",
    contractor_name: "Construcții Erbașu",
    contractor_slug: "constructii-erbasu",
    architect_name: "Graphic Studio Architecture",
    architect_slug: "graphic-studio-architecture",
    engineering_name: "Vital Engineering MEP",
    engineering_slug: "vital-engineering-mep",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Lujerului / Timișoara",
    address: "Bulevardul Timișoara 26, Bucharest",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 32000000,
    surface_area_sqm: 25000,
    floors: "12F",
    description: "25,000 sqm Grade A office tower adjacent to Plaza Romania shopping center.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://anchorgroup.ro", title: "Anchor Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-incity-residences-bucharest",
    name: "InCity Residences Bucharest",
    slug: "incity-residences-bucharest",
    developer_name: "Anchor Group Romania",
    developer_slug: "anchor-group",
    contractor_name: "Synergy Construct",
    contractor_slug: "synergy-construct",
    architect_name: "SYAA / Urban Landscape Architecture",
    architect_slug: "syaa-architecture",
    engineering_name: "Popaer Structural Engineering",
    engineering_slug: "popaer-structural-engineering",
    location: "Bucharest · Sector 3",
    location_slug: "bucharest-sector-3",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Vitan / Calea Vitan",
    address: "Calea Vitan 233, Bucharest",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 55000000,
    surface_area_sqm: 60000,
    unit_count: 500,
    floors: "17F",
    description: "4-building high-rise residential complex of 500 luxury apartments in central Bucharest Vitan area.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://incity.ro", title: "InCity Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-boemia-apartments-bucharest",
    name: "Boemia Apartments Bucharest",
    slug: "boemia-apartments-bucharest",
    developer_name: "Prima Development Group Oradea",
    developer_slug: "prima-development-oradea",
    contractor_name: "Concelex",
    contractor_slug: "concelex",
    architect_name: "Graphic Studio Architecture",
    architect_slug: "graphic-studio-architecture",
    engineering_name: "Blueprint Structural Engineering",
    engineering_slug: "blueprint-structural-engineering",
    location: "Bucharest · Sector 4",
    location_slug: "bucharest-sector-4",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Tineretului / Mărășești",
    address: "Bulevardul Mărășești 12, Bucharest",
    project_type: "Residential",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 15000000,
    surface_area_sqm: 12000,
    unit_count: 75,
    floors: "6F",
    description: "Boutique residential building of 75 high-end apartments near Tineretului Park in central Bucharest.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://primadevelopment.ro/boemia/", title: "Boemia Apartments Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-eli-park-bacau-logistics",
    name: "Eli Park Bacău Logistics Hub",
    slug: "eli-park-bacau-logistics",
    developer_name: "Element Industrial (Eli Parks)",
    developer_slug: "element-industrial-eli-parks",
    contractor_name: "Ness Proiect Europe",
    contractor_slug: "ness-proiect-europe",
    architect_name: "Plan31 Architecture & Engineering",
    architect_slug: "plan31-architecture",
    engineering_name: "Multinv MEP Engineering",
    engineering_slug: "multinv-mep-engineering",
    location: "Bacău · Bacău",
    location_slug: "bacau",
    county: "Bacău",
    locality: "Bacău",
    neighborhood: "A7 Highway Logistics Zone",
    address: "DN2 Bacău Bypass, Bacău",
    project_type: "Industrial/Logistics",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 20000000,
    surface_area_sqm: 30000,
    floors: "1F",
    description: "30,000 sqm Class A logistics warehouse along A7 Moldavia Motorway corridor.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://elementindustrial.ro/eli-park-bacau/", title: "Eli Park Bacău Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  }
];

let content = fs.readFileSync('lib/real-romanian-data.ts', 'utf-8');

// Insert final companies
const compPos = content.indexOf('export const realCompaniesDataset: RealCompany[] = [') + 'export const realCompaniesDataset: RealCompany[] = ['.length;
const compJson = finalCompanies.map(c => JSON.stringify(c, null, 2)).join(',\n');
content = content.slice(0, compPos) + '\n' + compJson + ',\n' + content.slice(compPos);

// Insert final projects
const projPos = content.indexOf('export const realProjectsDataset: RealProject[] = [') + 'export const realProjectsDataset: RealProject[] = ['.length;
const projJson = finalProjects.map(p => JSON.stringify(p, null, 2)).join(',\n');
content = content.slice(0, projPos) + '\n' + projJson + ',\n' + content.slice(projPos);

fs.writeFileSync('lib/real-romanian-data.ts', content, 'utf-8');
console.log('Successfully wrote final companies and projects expansion to lib/real-romanian-data.ts!');
