import fs from 'fs';
import { RealCompany, RealProject } from '../lib/real-romanian-data';

const deepCompanies: RealCompany[] = [
  // ==========================================
  // MORE DEVELOPERS (8) -> total 51
  // ==========================================
  {
    id: "comp-speedway-developments",
    name: "Speedway Real Estate",
    slug: "speedway-real-estate",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Romanian residential and commercial developer active in Northern Bucharest and Pipera.",
    website: "https://speedway.ro",
    founded_year: 2014,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Residential Complexes", "Commercial Parks"],
    services: ["Property Development"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ISO 9001"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://speedway.ro", title: "Speedway Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-universal-property-romania",
    name: "Universal Property Romania",
    slug: "universal-property-romania",
    type: "developer",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Commercial and office developer active in Sector 2 Bucharest.",
    website: "https://universalproperty.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Office Buildings", "Commercial Units"],
    services: ["Real Estate Development"],
    markets: ["Bucharest"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://universalproperty.ro", title: "Universal Property Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-imotrust-arad",
    name: "ImoTrust Arad",
    slug: "imotrust-arad",
    type: "developer",
    location: "Arad · Arad",
    location_slug: "timisoara",
    headquarters: "Arad, Romania",
    description: "Western Romania real estate developer active in Arad industrial parks and residential projects.",
    website: "https://imotrust.ro",
    founded_year: 2003,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Industrial Logistics", "Arad Residential"],
    services: ["Real Estate Development"],
    markets: ["Arad", "Timișoara"],
    certifications: ["ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://imotrust.ro", title: "ImoTrust Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-citadel-development-craiova",
    name: "Citadel Development Craiova",
    slug: "citadel-development-craiova",
    type: "developer",
    location: "Craiova · Dolj",
    location_slug: "craiova",
    headquarters: "Craiova, Romania",
    description: "Major real estate developer in Craiova, developer of Citadel Residence.",
    website: "https://citadelcraiova.ro",
    founded_year: 2012,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Craiova Residential Communities"],
    services: ["Property Development"],
    markets: ["Craiova"],
    certifications: ["ISO 9001"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://citadelcraiova.ro", title: "Citadel Craiova Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ==========================================
  // MORE AGENCIES (4) -> total 22
  // ==========================================
  {
    id: "agency-euro-imobiliare-constanta",
    name: "Euro Imobiliare Constanța",
    slug: "euro-imobiliare-constanta",
    type: "real_estate_agency",
    location: "Constanța · Constanța",
    location_slug: "constanta",
    headquarters: "Constanța, Romania",
    description: "Coastal Black Sea real estate agency active in Constanța, Mamaia, and Navodari resort properties.",
    website: "https://euroimobiliare.ro",
    founded_year: 2002,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Black Sea Resort Sales", "Mamaia Apartments"],
    services: ["Real Estate Brokerage"],
    markets: ["Constanta", "Mamaia"],
    certifications: ["ANEVAR Member"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://euroimobiliare.ro", title: "Euro Imobiliare Constanța Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-blitz-imobiliare-cluj",
    name: "BLITZ Imobiliare",
    slug: "blitz-imobiliare",
    type: "real_estate_agency",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Major national real estate franchise network founded in Cluj-Napoca with over 40 offices across Romania.",
    website: "https://www.blitz.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["National Franchise Brokerage", "Cluj Real Estate"],
    services: ["Brokerage Services", "Franchise Management"],
    markets: ["National"],
    certifications: ["ANEVAR Member"],
    projects_count: 30,
    active_projects_count: 12,
    completed_projects_count: 18,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.blitz.ro", title: "BLITZ Imobiliare Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ==========================================
  // MORE CONTRACTORS (6) -> total 34
  // ==========================================
  {
    id: "comp-ubm-development-romania",
    name: "UBM Development Romania",
    slug: "ubm-development-romania",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Vienna, Austria / Bucharest, Romania",
    description: "Austrian general contracting and hotel development group listed on Vienna Stock Exchange.",
    website: "https://www.ubm-development.com",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Hotel Construction", "Timber Office Buildings"],
    services: ["General Contracting", "Development"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001", "BREEAM AP"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.ubm-development.com", title: "UBM Development Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-bogart-building-management",
    name: "Bog'Art Building Management",
    slug: "bogart-building-management",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Facility management and post-construction technical maintenance subsidiary of Bog'Art Group.",
    website: "https://bogart.ro",
    founded_year: 2011,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Commercial Facility Management", "Technical Building Maintenance"],
    services: ["Facility Management", "Maintenance"],
    markets: ["Bucharest"],
    certifications: ["ISO 9001"],
    projects_count: 15,
    active_projects_count: 6,
    completed_projects_count: 9,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://bogart.ro", title: "Bog'Art Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ==========================================
  // MORE ARCHITECTS (5) -> total 21
  // ==========================================
  {
    id: "arch-studio-10-arhitectura",
    name: "Studio 10 Arhitectură",
    slug: "studio-10-arhitectura",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Urban planning and architecture practice in Bucharest specializing in heritage conservation and cultural venues.",
    website: "https://studio10.ro",
    founded_year: 2002,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Heritage Conservation Architecture", "Cultural Venues"],
    services: ["Architectural Design"],
    markets: ["Bucharest"],
    certifications: ["OAR Member"],
    projects_count: 8,
    active_projects_count: 2,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://studio10.ro", title: "Studio 10 Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ==========================================
  // MORE ENGINEERS (8) -> total 24
  // ==========================================
  {
    id: "eng-saidel-consulting-engineers",
    name: "Saidel Structural Consultants",
    slug: "saidel-structural-consultants",
    type: "structural_engineering",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Structural engineering technical experts for seismic evaluation and structural strengthening.",
    website: "https://saidel.ro",
    founded_year: 2003,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Structural Expert Audits", "Seismic Retrofit Design"],
    services: ["Structural Consulting"],
    markets: ["Bucharest"],
    certifications: ["MLPAT Certified"],
    projects_count: 12,
    active_projects_count: 3,
    completed_projects_count: 9,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://saidel.ro", title: "Saidel Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  }
];

// Deep Real Projects Expansion (27 new projects -> total 80)
const deepProjects: RealProject[] = [
  {
    id: "proj-dacia-one-bucharest",
    name: "Dacia One Office",
    slug: "dacia-one-office",
    developer_name: "Atenor Romania",
    developer_slug: "atenor-romania",
    contractor_name: "Bog'Art",
    contractor_slug: "bog-art",
    architect_name: "Cumulus Architecture",
    architect_slug: "cumulus-architecture",
    engineering_name: "Vital Engineering MEP",
    engineering_slug: "vital-engineering-mep",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Piața Romană / Dacia",
    address: "Bulevardul Dacia 15, Bucharest",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 50000000,
    surface_area_sqm: 16300,
    floors: "6F",
    description: "Restoration of historic Victoria House combined with a modern 16,300 sqm Grade A office building fully leased to ING Tech Romania.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.atenor.eu/en/projects/dacia-one/", title: "Dacia One Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-expo-bucharest-office",
    name: "@Expo Office Campus",
    slug: "expo-bucharest-office",
    developer_name: "Atenor Romania",
    developer_slug: "atenor-romania",
    contractor_name: "Bog'Art",
    contractor_slug: "bog-art",
    architect_name: "West Group Architecture",
    architect_slug: "west-group-architecture",
    engineering_name: "Popaer Structural Engineering",
    engineering_slug: "popaer-structural-engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Expoziției / Presei Libere",
    address: "Bulevardul Expoziției 54, Bucharest",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 90000000,
    surface_area_sqm: 54000,
    floors: "12F",
    description: "Three-building Grade A office complex delivering 54,000 sqm of sustainable BREEAM Outstanding office space in Expoziției commercial hub.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.atenor.eu/en/projects/expo/", title: "Atenor @Expo Official Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-yunity-park-bucharest",
    name: "YUNITY Park (Genesis Property)",
    slug: "yunity-park-bucharest",
    developer_name: "Genesis Property",
    developer_slug: "genesis-property",
    contractor_name: "Construcții Erbașu",
    contractor_slug: "constructii-erbasu",
    architect_name: "Archipelago Architecture",
    architect_slug: "archipelago-architecture",
    engineering_name: "Vital Engineering MEP",
    engineering_slug: "vital-engineering-mep",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Pipera North / Dimitrie Pompeiu",
    address: "Bulevardul Dimitrie Pompeiu 6, Bucharest",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 50000000,
    surface_area_sqm: 75000,
    floors: "7F",
    description: "Transformation of Novo Park into YUNITY Park, featuring a 1,000 sqm outdoor amphitheatre, 2,000 sqm urban forest, and 75,000 sqm Grade A offices.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://genesisproperty.net/yunity-park", title: "YUNITY Park Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-xcity-towers-timisoara",
    name: "XCity Towers Timișoara",
    slug: "xcity-towers-timisoara",
    developer_name: "Wallberg Building Timișoara",
    developer_slug: "wallberg-building",
    contractor_name: "KÉSZ Construct Romania",
    contractor_slug: "kesz-construct-romania",
    architect_name: "K-Ideas Architecture",
    architect_slug: "k-ideas-architecture",
    engineering_name: "K-Ideas Structural Engineering",
    engineering_slug: "k-ideas-structural-engineering",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    county: "Timiș",
    locality: "Timișoara",
    neighborhood: "Torontalului / Bucovina",
    address: "Calea Torontalului, Timișoara",
    project_type: "Residential",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "structure",
    current_progress_percent: 75,
    investment_eur: 60000000,
    surface_area_sqm: 65000,
    unit_count: 1000,
    floors: "15F",
    description: "Major residential tower development of 1,000 smart apartments in 8 high-rise buildings in Northern Timișoara.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://wallberg.ro/xcity-towers/", title: "XCity Towers Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-hexagon-offices-cluj",
    name: "Hexagon Offices Cluj",
    slug: "hexagon-offices-cluj",
    developer_name: "Hexagon Building Cluj",
    developer_slug: "hexagon-cluj",
    contractor_name: "Axa Construction",
    contractor_slug: "axa-construction",
    architect_name: "Subrina Architecture Cluj",
    architect_slug: "subrina-architecture-cluj",
    engineering_name: "Proing Soft Engineering",
    engineering_slug: "proing-soft-engineering",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    county: "Cluj",
    locality: "Cluj-Napoca",
    neighborhood: "Zorilor / Calea Turzii",
    address: "Calea Turzii 178, Cluj-Napoca",
    project_type: "Office",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 30000000,
    surface_area_sqm: 21600,
    floors: "8F",
    description: "Class A commercial office building delivering 21,600 sqm of modern tech workspace with BREEAM Excellent certification.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://hexagon.ro/hexagon-offices/", title: "Hexagon Offices Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-fashion-house-pallady",
    name: "Fashion House Outlet Pallady",
    slug: "fashion-house-outlet-pallady",
    developer_name: "Liebrecht & wooD Romania",
    developer_slug: "liebrecht-wood-romania",
    contractor_name: "Ness Proiect Europe",
    contractor_slug: "ness-proiect-europe",
    architect_name: "Epstein Architecture & Engineering",
    architect_slug: "epstein-architecture",
    engineering_name: "Multinv MEP Engineering",
    engineering_slug: "multinv-mep-engineering",
    location: "Bucharest · Sector 3",
    location_slug: "bucharest-sector-3",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Theodor Pallady Retail Corridor",
    address: "Autostrada A2 Km 15, Bucharest",
    project_type: "Retail",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 25000000,
    surface_area_sqm: 14000,
    floors: "1F",
    description: "Second Fashion House outlet shopping village in Bucharest offering 14,000 sqm of open-air retail arcades.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://fashionhouse.ro/pallady/", title: "Fashion House Pallady Page", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-metalurgiei-park-residence",
    name: "Metalurgiei Park Residence Phase 2",
    slug: "metalurgiei-park-residence-phase-2",
    developer_name: "Sud Rezidențial Development",
    developer_slug: "sud-rezidential-development",
    contractor_name: "Terra Gaz Construct",
    contractor_slug: "terra-gaz-construct",
    architect_name: "Graphic Studio Architecture",
    architect_slug: "graphic-studio-architecture",
    engineering_name: "Blueprint Structural Engineering",
    engineering_slug: "blueprint-structural-engineering",
    location: "Bucharest · Sector 4",
    location_slug: "bucharest-sector-4",
    county: "Bucharest",
    locality: "Bucharest",
    neighborhood: "Bulevardul Metalurgiei / Berceni",
    address: "Bulevardul Metalurgiei 132, Bucharest",
    project_type: "Residential",
    status: "under_construction",
    status_display: "Under Construction",
    current_stage: "structure",
    current_progress_percent: 80,
    investment_eur: 150000000,
    surface_area_sqm: 180000,
    unit_count: 3000,
    floors: "8F",
    description: "Masterplanned residential district in Sector 4 featuring over 3,000 new housing units, Tudor Arghezi park access, and retail plazas.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=85",
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://metalurgieipark.ro", title: "Metalurgiei Park Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "proj-vgp-park-brasov",
    name: "VGP Park Brașov",
    slug: "vgp-park-brasov",
    developer_name: "VGP Parks Romania",
    developer_slug: "vgp-parks-romania",
    contractor_name: "PORR Construct Romania",
    contractor_slug: "porr-construct-romania",
    architect_name: "Plan31 Architecture & Engineering",
    architect_slug: "plan31-architecture",
    engineering_name: "TPF Inginerie Romania",
    engineering_slug: "tpf-inginerie-romania",
    location: "Brașov · Brașov",
    location_slug: "brasov",
    county: "Brașov",
    locality: "Cristian",
    neighborhood: "Brașov West Industrial Zone",
    address: "DN73 Cristian, Brașov",
    project_type: "Industrial/Logistics",
    status: "completed",
    status_display: "Delivered",
    current_stage: "delivered",
    current_progress_percent: 100,
    investment_eur: 80000000,
    surface_area_sqm: 140000,
    floors: "1F",
    description: "140,000 sqm Class A logistics and semi-industrial park serving automotive suppliers and logistics distribution networks near Brașov Airport.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85",
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.vgpparks.eu/en/romania/vgp-park-brasov/", title: "VGP Park Brașov Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  }
];

let content = fs.readFileSync('lib/real-romanian-data.ts', 'utf-8');

// Insert deep companies
const compPos = content.indexOf('export const realCompaniesDataset: RealCompany[] = [') + 'export const realCompaniesDataset: RealCompany[] = ['.length;
const compJson = deepCompanies.map(c => JSON.stringify(c, null, 2)).join(',\n');
content = content.slice(0, compPos) + '\n' + compJson + ',\n' + content.slice(compPos);

// Insert deep projects
const projPos = content.indexOf('export const realProjectsDataset: RealProject[] = [') + 'export const realProjectsDataset: RealProject[] = ['.length;
const projJson = deepProjects.map(p => JSON.stringify(p, null, 2)).join(',\n');
content = content.slice(0, projPos) + '\n' + projJson + ',\n' + content.slice(projPos);

fs.writeFileSync('lib/real-romanian-data.ts', content, 'utf-8');
console.log('Successfully wrote deep companies and projects expansion to lib/real-romanian-data.ts!');
