import fs from 'fs';
import { RealCompany, RealProject } from '../lib/real-romanian-data';

// Phase 22 + 23 Real Companies Expansion Dataset
const additionalCompanies: RealCompany[] = [
  // ==========================================
  // DEVELOPERS (25 new entries -> total 48)
  // ==========================================
  {
    id: "comp-granvia-romania",
    name: "Granvia Real Estate Romania",
    slug: "granvia-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Madrid, Spain / Bucharest, Romania",
    description: "Spanish real estate developer active in Romania since 2007, developer of Granvia Park Lujerului, Timișoara 58, and Avangarde Forest.",
    website: "https://granvia.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Residential Complexes", "Urban Infill Projects"],
    services: ["Property Development", "Sales"],
    markets: ["Bucharest", "Constanta"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 1,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://granvia.ro", title: "Granvia Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-cordia-romania",
    name: "Cordia Romania (Futureal Group)",
    slug: "cordia-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Budapest, Hungary / Bucharest, Romania",
    description: "Major CEE residential developer member of Futureal Group, developer of Parcului 20 and Coral Park in northern Bucharest.",
    website: "https://cordiahomes.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Smart-Home Residential Complexes", "Green Residential Towers"],
    services: ["Real Estate Development", "Asset Management"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Excellent"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://cordiahomes.ro", title: "Cordia Romania Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-atenor-romania",
    name: "Atenor Romania",
    slug: "atenor-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "La Hulpe, Belgium / Bucharest, Romania",
    description: "Belgian urban real estate developer listed on Euronext Brussels, developer of Hermes Business Campus, Dacia One, @Expo, and UP-site Bucharest.",
    website: "https://www.atenor.eu",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["High-End Sustainable Office Campuses", "Luxury Residential Towers"],
    services: ["Real Estate Development", "Urban Architecture"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Outstanding", "WELL Platinum"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.atenor.eu", title: "Atenor Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-primavera-development",
    name: "Primavera Development",
    slug: "primavera-development",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Boutique Romanian real estate developer known for Muse Office, Frumoasa Office, and premium residential projects in northern Bucharest.",
    website: "https://primaveradevelopment.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Boutique Office Buildings", "Exclusive Residential Properties"],
    services: ["Property Development", "Investment"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Excellent"],
    projects_count: 5,
    active_projects_count: 1,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://primaveradevelopment.ro", title: "Primavera Development Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-rock-development-holding",
    name: "Rock Development Holding",
    slug: "rock-development-holding",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Romanian investment and real estate development group, developer of Avrig 35 Residential and luxury mountain resorts in Poiana Brașov.",
    website: "https://rockdevelopment.ro",
    founded_year: 2018,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Urban Residential Neighborhoods", "Poiana Brașov Hospitality Resorts"],
    services: ["Real Estate Development", "Hospitality Management"],
    markets: ["Bucharest", "Brasov"],
    certifications: ["ISO 9001"],
    projects_count: 4,
    active_projects_count: 2,
    completed_projects_count: 2,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://rockdevelopment.ro", title: "Rock Development Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-liebrecht-wood-romania",
    name: "Liebrecht & wooD Romania",
    slug: "liebrecht-wood-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Warsaw, Poland / Bucharest, Romania",
    description: "European commercial real estate developer, owner and developer of Fashion House Outlet Center Militari, Fashion House Pallady, and Liziera de Lac residential park.",
    website: "https://liebrecht-wood.com",
    founded_year: 2001,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Outlet Shopping Centers", "Suburban Green Residential Communities"],
    services: ["Commercial Real Estate Development", "Asset Management"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["BREEAM Very Good"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://liebrecht-wood.com", title: "Liebrecht & wooD Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-sud-rezidential-development",
    name: "Sud Rezidențial Development",
    slug: "sud-rezidential-development",
    type: "developer",
    location: "Bucharest · Sector 4",
    location_slug: "bucharest-sector-4",
    headquarters: "Bucharest, Romania",
    description: "Major residential development consortium in Southern Bucharest, developer of Metalurgiei Park Residence and Apollo Residence.",
    website: "https://sudrezidential.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Large-Scale Suburban Residential Parks"],
    services: ["Property Development", "Sales Management"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ISO 9001"],
    projects_count: 12,
    active_projects_count: 4,
    completed_projects_count: 8,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://sudrezidential.ro", title: "Sud Rezidențial Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-edil-constructii-cluj",
    name: "Edil Construcții Cluj",
    slug: "edil-constructii-cluj",
    type: "developer",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Established Transylvanian developer active in Cluj-Napoca residential and commercial sectors for over 20 years.",
    website: "https://edil.ro",
    founded_year: 2001,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Cluj Residential Complexes", "Commercial Assets"],
    services: ["Real Estate Development", "General Contracting"],
    markets: ["Cluj-Napoca"],
    certifications: ["ISO 9001"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://edil.ro", title: "Edil Cluj Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-sedako-group-timisoara",
    name: "Sedako Group Timișoara",
    slug: "sedako-group-timisoara",
    type: "developer",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Prominent real estate developer in Timișoara, developer of Sedako Park and central urban apartment buildings.",
    website: "https://sedako.ro",
    founded_year: 2003,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Timișoara Urban Apartments", "Commercial Plazas"],
    services: ["Property Development", "Asset Leasing"],
    markets: ["Timișoara"],
    certifications: ["ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://sedako.ro", title: "Sedako Timișoara Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-iulius-real-estate-iasi",
    name: "IULIUS Real Estate Iași",
    slug: "iulius-real-estate-iasi",
    type: "developer",
    location: "Iași · Iași",
    location_slug: "iasi",
    headquarters: "Iași, Romania",
    description: "Leading Romanian developer of mixed-use urban regeneration projects including Palas Iași, Palas Campus, and Iulius Malls in Iași, Cluj, Suceava, and Timișoara.",
    website: "https://iuliuscompany.ro",
    founded_year: 1991,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Urban Regeneration Projects", "United Business Centers", "Regional Shopping Malls"],
    services: ["Real Estate Development", "Property Management", "Leasing"],
    markets: ["Iași", "Cluj-Napoca", "Timișoara", "Suceava"],
    certifications: ["LEED Gold", "LEED Platinum", "WELL Health-Safety"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://iuliuscompany.ro", title: "IULIUS Company Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-qualis-properties-brasov",
    name: "Qualis Properties Brașov",
    slug: "qualis-properties-brasov",
    type: "developer",
    location: "Brașov · Brașov",
    location_slug: "brasov",
    headquarters: "Brașov, Romania",
    description: "Fast-growing residential real estate developer in Brașov, developer of Qualis 1, Qualis 2, and Qualis City in Tractorul neighborhood.",
    website: "https://qualis.ro",
    founded_year: 2017,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Brașov Smart Residential Complexes"],
    services: ["Property Development", "Sales"],
    markets: ["Brașov"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://qualis.ro", title: "Qualis Properties Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-prima-development-oradea",
    name: "Prima Development Group Oradea",
    slug: "prima-development-oradea",
    type: "developer",
    location: "Oradea · Bihor",
    location_slug: "oradea",
    headquarters: "Oradea, Romania",
    description: "Premier real estate developer in Western Romania expanding into Bucharest, developer of Boavista, Prima Nufărul, and Boemia Apartments.",
    website: "https://primadevelopment.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Oradea Residential Complexes", "Bucharest Infill Communities"],
    services: ["Real Estate Development", "Construction Management"],
    markets: ["Oradea", "Bucharest"],
    certifications: ["ISO 9001"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://primadevelopment.ro", title: "Prima Development Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-alinso-group-pwp",
    name: "Alinso Group (PWP Parks)",
    slug: "alinso-group-pwp",
    type: "developer",
    location: "Ploiești · Prahova",
    location_slug: "ploiesti",
    headquarters: "Zwijnaarde, Belgium / Ploiești, Romania",
    description: "International industrial developer, developer and operator of Ploiești West Park (300-hectare industrial and logistics park).",
    website: "https://alinso.eu",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Built-to-Suit Logistics Hubs", "Intermodal Industrial Parks"],
    services: ["Industrial Park Development", "Asset Management"],
    markets: ["Prahova", "Bucharest Corridor"],
    certifications: ["BREEAM Very Good"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://alinso.eu", title: "Alinso Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-vgp-parks-romania",
    name: "VGP Parks Romania",
    slug: "vgp-parks-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Antwerp, Belgium / Bucharest, Romania",
    description: "Pan-European logistics developer listed on Euronext Brussels, developer of VGP Park Timișoara, VGP Park Brașov, and VGP Park Bucharest North.",
    website: "https://www.vgpparks.eu",
    founded_year: 2007,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Class A Logistics Warehouses", "Semi-Industrial Parks"],
    services: ["Industrial Property Development", "Asset Leasing"],
    markets: ["Timișoara", "Brașov", "Bucharest", "Arad"],
    certifications: ["DGNB Gold", "BREEAM Excellent"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.vgpparks.eu", title: "VGP Parks Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-element-industrial-eli-parks",
    name: "Element Industrial (Eli Parks)",
    slug: "element-industrial-eli-parks",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Romanian logistics and industrial park developer, developer of Eli Park Bucharest (Buftea), Eli Park Bacău, and Eli Park Brăila.",
    website: "https://elementindustrial.ro",
    founded_year: 2018,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Class A Logistics Distribution Parks"],
    services: ["Industrial Real Estate Development", "Property Management"],
    markets: ["Bucharest Corridor", "Bacau", "Braila", "Ploiesti"],
    certifications: ["BREEAM Very Good"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://elementindustrial.ro", title: "Element Industrial Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-anchor-group",
    name: "Anchor Group Romania",
    slug: "anchor-group",
    type: "developer",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    headquarters: "Bucharest, Romania",
    description: "Pioneer commercial real estate developer in Romania since 1997, developer of Plaza Romania, București Mall, Anchor Plaza office, and InCity Residences.",
    website: "https://anchorgroup.ro",
    founded_year: 1997,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Shopping Centers", "Grade A Office Buildings", "Residential Developments"],
    services: ["Property Development", "Asset Management", "Retail Leasing"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Very Good", "ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://anchorgroup.ro", title: "Anchor Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-wallberg-building",
    name: "Wallberg Building Timișoara",
    slug: "wallberg-building",
    type: "developer",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Premium residential developer operating in Western Romania and Arad, developer of XCity Towers Timișoara and Arad Plaza.",
    website: "https://wallberg.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["High-Rise Residential Towers", "Smart Apartment Complexes"],
    services: ["Real Estate Development", "Project Management"],
    markets: ["Timișoara", "Arad"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://wallberg.ro", title: "Wallberg Building Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-hexagon-cluj",
    name: "Hexagon Building Cluj",
    slug: "hexagon-cluj",
    type: "developer",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Commercial and office property developer in Cluj-Napoca, developer of Hexagon Offices, residential projects, and logistics hubs in Transylvania.",
    website: "https://hexagon.ro",
    founded_year: 2012,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Grade A Office Parks", "Mixed-Use Cluj Projects"],
    services: ["Real Estate Investment", "Project Development"],
    markets: ["Cluj-Napoca"],
    certifications: ["BREEAM Excellent"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://hexagon.ro", title: "Hexagon Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-genesis-property",
    name: "Genesis Property",
    slug: "genesis-property",
    type: "developer",
    location: "Bucharest · Sector 6",
    location_slug: "bucharest-sector-6",
    headquarters: "Bucharest, Romania",
    description: "Leading Romanian commercial real estate owner and developer, owner of YUNITY Park (formerly Novo Park) and West Gate Business District.",
    website: "https://genesisproperty.net",
    founded_year: 2002,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Office Campuses", "Business Parks", "IMMUNE Certified Buildings"],
    services: ["Commercial Real Estate Development", "Asset Management"],
    markets: ["Bucharest"],
    certifications: ["BREEAM Outstanding", "WELL Health-Safety"],
    projects_count: 4,
    active_projects_count: 1,
    completed_projects_count: 3,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://genesisproperty.net", title: "Genesis Property Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-plaza-centers-romania",
    name: "Plaza Centers Romania",
    slug: "plaza-centers-romania",
    type: "developer",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Amsterdam, Netherlands / Bucharest, Romania",
    description: "International retail and commercial developer active in Central and Eastern Europe, developer of Casa Radio site and regional shopping centers.",
    website: "https://www.plazacenters.com",
    founded_year: 2005,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Shopping Centers", "Urban Commercial Projects"],
    services: ["Commercial Development", "Asset Management"],
    markets: ["Bucharest", "Timisoara", "Miercurea Ciuc"],
    certifications: ["ISO 9001"],
    projects_count: 5,
    active_projects_count: 1,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.plazacenters.com", title: "Plaza Centers Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ==========================================
  // REAL ESTATE AGENCIES (18 entries -> total 18)
  // ==========================================
  {
    id: "agency-svn-romania",
    name: "SVN Romania",
    slug: "svn-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Leading real estate advisory firm in Romania, exclusive sales agent for major residential developments across Bucharest and major regional hubs.",
    website: "https://svn.ro",
    founded_year: 2019,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Residential Project Sales", "Property Management", "Commercial Advisory"],
    services: ["Project Sales", "Tenant Advisory", "Valuation Services"],
    markets: ["Bucharest", "Cluj-Napoca", "Brașov", "Constanța"],
    certifications: ["ANEVAR Accredited"],
    projects_count: 20,
    active_projects_count: 8,
    completed_projects_count: 12,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://svn.ro", title: "SVN Romania Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-crosspoint-real-estate",
    name: "Crosspoint Real Estate",
    slug: "crosspoint-real-estate",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "International Associate of Savills in Romania, providing transaction management, capital markets advisory, and luxury residential brokerage.",
    website: "https://crosspoint.com.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Capital Markets Advisory", "Commercial Leasing", "Luxury Residential"],
    services: ["Investment Advisory", "Corporate Services"],
    markets: ["Bucharest", "National"],
    certifications: ["Savills International Associate"],
    projects_count: 15,
    active_projects_count: 5,
    completed_projects_count: 10,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://crosspoint.com.ro", title: "Crosspoint Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-knight-frank-romania",
    name: "Knight Frank Romania",
    slug: "knight-frank-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "London, UK / Bucharest, Romania",
    description: "Global commercial real estate consultancy advising institutional investors, office developers, and international occupiers in Romania.",
    website: "https://knightfrank.ro",
    founded_year: 2009,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Office Agency", "Industrial & Logistics", "Capital Markets"],
    services: ["Tenant Representation", "Landlord Representation", "Research"],
    markets: ["Bucharest", "National"],
    certifications: ["RICS Certified"],
    projects_count: 18,
    active_projects_count: 6,
    completed_projects_count: 12,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://knightfrank.ro", title: "Knight Frank Romania Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-cushman-wakefield-echinox",
    name: "Cushman & Wakefield Echinox",
    slug: "cushman-wakefield-echinox",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Exclusive affiliate of Cushman & Wakefield in Romania, leading commercial real estate services firm providing asset services, valuation, and research.",
    website: "https://cwechinox.com",
    founded_year: 1993,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Retail Leasing", "Office Agency", "Property Asset Management"],
    services: ["Valuation", "Tenant Advisory", "Research Reports"],
    markets: ["Bucharest", "National"],
    certifications: ["ANEVAR Member", "RICS Certified"],
    projects_count: 22,
    active_projects_count: 9,
    completed_projects_count: 13,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://cwechinox.com", title: "C&W Echinox Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-colliers-romania",
    name: "Colliers Romania",
    slug: "colliers-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Toronto, Canada / Bucharest, Romania",
    description: "Leading diversified professional services and investment management company advising real estate occupiers and owners in Romania for over 25 years.",
    website: "https://www.colliers.com/ro-ro",
    founded_year: 1996,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Land Agency", "ESG Advisory", "Industrial & Logistics Services"],
    services: ["Capital Markets", "Valuation Advisory", "Workplace Advisory"],
    markets: ["Bucharest", "National"],
    certifications: ["RICS Certified", "ANEVAR Member"],
    projects_count: 25,
    active_projects_count: 10,
    completed_projects_count: 15,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.colliers.com/ro-ro", title: "Colliers Romania Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-jll-romania",
    name: "JLL Romania (Jones Lang LaSalle)",
    slug: "jll-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Chicago, USA / Bucharest, Romania",
    description: "Fortune 500 professional services firm specializing in real estate and investment management active in the Romanian commercial property market.",
    website: "https://www.jll.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Corporate Solutions", "Capital Markets", "Project Development Services"],
    services: ["Tenant Advisory", "Property Management"],
    markets: ["Bucharest", "National"],
    certifications: ["RICS Certified"],
    projects_count: 20,
    active_projects_count: 7,
    completed_projects_count: 13,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.jll.ro", title: "JLL Romania Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-premier-estate-management",
    name: "Premier Estate Management",
    slug: "premier-estate-management",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Specialized residential project sales and consultancy company managing residential portfolio launches across Bucharest.",
    website: "https://premier-estate.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Residential New-Build Sales", "Developer Advisory"],
    services: ["Exclusive Project Sales", "Marketing Management"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member"],
    projects_count: 12,
    active_projects_count: 4,
    completed_projects_count: 8,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://premier-estate.ro", title: "Premier Estate Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-imoteca-real-estate-experts",
    name: "Imoteca — Real Estate Experts",
    slug: "imoteca-real-estate-experts",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Residential consultancy firm providing project marketing, tenant representation, and sales for medium-to-luxury housing developments.",
    website: "https://imoteca.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["New Residential Developments", "Boutique Housing Sales"],
    services: ["Residential Sales", "Investment Consulting"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member"],
    projects_count: 10,
    active_projects_count: 3,
    completed_projects_count: 7,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://imoteca.ro", title: "Imoteca Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-sud-rezidential-real-estate",
    name: "Sud Rezidențial Real Estate Agency",
    slug: "sud-rezidential-real-estate",
    type: "real_estate_agency",
    location: "Bucharest · Sector 4",
    location_slug: "bucharest-sector-4",
    headquarters: "Bucharest, Romania",
    description: "Dedicated residential sales and brokerage hub operating across Southern Bucharest and Ilfov counties.",
    website: "https://www.sudrezidential.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Southern Bucharest Housing", "New Apartment Complexes"],
    services: ["Project Brokerage", "Mortgage Advisory"],
    markets: ["Bucharest Sector 4", "Ilfov South"],
    certifications: ["ANEVAR Member"],
    projects_count: 14,
    active_projects_count: 5,
    completed_projects_count: 9,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.sudrezidential.ro", title: "Sud Rezidențial Brokerage Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-north-bucharest-investments",
    name: "North Bucharest Investments",
    slug: "north-bucharest-investments",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Specialized real estate agency focusing on high-end residential sales and investor portfolio acquisitions in Northern Bucharest.",
    website: "https://northbucharestinvestments.ro",
    founded_year: 2020,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Northern Bucharest Luxury Apartments", "Investor Property Portfolios"],
    services: ["Residential Sales", "Asset Advisory"],
    markets: ["Bucharest Sector 1", "Piper North"],
    certifications: ["ANEVAR Member"],
    projects_count: 8,
    active_projects_count: 4,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://northbucharestinvestments.ro", title: "North Bucharest Investments Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-skol-imobiliare-cluj",
    name: "Skol Imobiliare Cluj",
    slug: "skol-imobiliare-cluj",
    type: "real_estate_agency",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Established Transylvanian real estate brokerage specializing in Cluj-Napoca commercial land and residential developments.",
    website: "https://skolimobiliare.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Cluj Residential Resales", "Commercial Land Acquisition"],
    services: ["Brokerage Services", "Land Advisory"],
    markets: ["Cluj-Napoca"],
    certifications: ["ANEVAR Member"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://skolimobiliare.ro", title: "Skol Imobiliare Cluj Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-realpro-romania",
    name: "Realpro Romania",
    slug: "realpro-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Exclusive representation residential brokerage network providing seller agency services across major Romanian cities.",
    website: "https://realpro.ro",
    founded_year: 2009,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Exclusive Seller Representation"],
    services: ["Residential Representation", "Marketing"],
    markets: ["Bucharest", "Brașov", "Constanța"],
    certifications: ["ANEVAR Member"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://realpro.ro", title: "Realpro Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-regus-romania-iwg",
    name: "Regus Romania (IWG Group)",
    slug: "regus-romania-iwg",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Zug, Switzerland / Bucharest, Romania",
    description: "Flexible workplace operator member of IWG Group, operating over 15 business flex-work centers across Bucharest, Cluj-Napoca, Timișoara, and Iași.",
    website: "https://www.regus.com/ro-ro",
    founded_year: 1999,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Flexible Workspace Leasing", "Co-Working Hubs", "Enterprise Flex Office"],
    services: ["Flex Office Management", "Corporate Workspace"],
    markets: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"],
    certifications: ["ISO 9001"],
    projects_count: 15,
    active_projects_count: 6,
    completed_projects_count: 9,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.regus.com/ro-ro", title: "Regus Romania Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-green-angels-real-estate",
    name: "Green Angels Real Estate",
    slug: "green-angels-real-estate",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Boutique sustainable real estate advisory specializing in green certified residential properties and nZEB developments.",
    website: "https://greenangels.ro",
    founded_year: 2015,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["nZEB Housing Representation", "Green Certified Homes"],
    services: ["Residential Advisory", "Sustainability Consulting"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member", "ROGBC Member"],
    projects_count: 5,
    active_projects_count: 2,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://greenangels.ro", title: "Green Angels Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-euroest-imobiliare",
    name: "Euroest Imobiliare",
    slug: "euroest-imobiliare",
    type: "real_estate_agency",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Long-standing commercial and industrial real estate agency operating in Bucharest for over 25 years.",
    website: "https://euroest.ro",
    founded_year: 1994,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Industrial & Land Transactions", "Commercial Property Sales"],
    services: ["Brokerage Services", "Land Advisory"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ANEVAR Member"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://euroest.ro", title: "Euroest Imobiliare Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-avison-young-romania",
    name: "Avison Young Romania",
    slug: "avison-young-romania",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Toronto, Canada / Bucharest, Romania",
    description: "Principal-led global commercial real estate services firm providing transaction, valuation, tenant representation, and capital markets advisory.",
    website: "https://www.avisonyoung.ro",
    founded_year: 2017,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Tenant Representation", "Capital Markets", "Valuation Advisory"],
    services: ["Commercial Leasing", "Property Valuation", "Research"],
    markets: ["Bucharest", "National"],
    certifications: ["RICS Accredited", "ANEVAR Member"],
    projects_count: 9,
    active_projects_count: 4,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.avisonyoung.ro", title: "Avison Young Romania Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-remax-romania",
    name: "RE/MAX Romania",
    slug: "remax-romania",
    type: "real_estate_agency",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Largest real estate franchise brokerage network in Romania with over 60 offices and 1,000 real estate agents operating across major Romanian cities.",
    website: "https://www.remax.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["National Franchise Brokerage Network", "Residential Resales & New Builds"],
    services: ["Real Estate Brokerage", "Franchise Management"],
    markets: ["National"],
    certifications: ["ANEVAR Member"],
    projects_count: 25,
    active_projects_count: 10,
    completed_projects_count: 15,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.remax.ro", title: "RE/MAX Romania Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "agency-nordis-real-estate",
    name: "Nordis Real Estate Agency",
    slug: "nordis-real-estate-agency",
    type: "real_estate_agency",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Real estate agency specializing in luxury residential sales, holiday hotel apartments, and investment management.",
    website: "https://nordis.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Luxury Apartment Sales", "Resort Hotel Investments"],
    services: ["Real Estate Brokerage", "Investment Sales"],
    markets: ["Bucharest", "Constanta", "Brasov"],
    certifications: ["ANEVAR Member"],
    projects_count: 6,
    active_projects_count: 3,
    completed_projects_count: 3,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://nordis.ro", title: "Nordis Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ==========================================
  // CONTRACTORS (20 entries -> total 31)
  // ==========================================
  {
    id: "comp-terra-gaz-construct",
    name: "Terra Gaz Construct",
    slug: "terra-gaz-construct",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Major general contractor active in residential high-rises, utility networks, and public infrastructure works.",
    website: "https://terragaz.ro",
    founded_year: 1998,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["High-Rise Structural Contracting", "Civic Infrastructure"],
    services: ["General Contracting", "Civil Engineering"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 14,
    active_projects_count: 4,
    completed_projects_count: 10,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://terragaz.ro", title: "Terra Gaz Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-ness-proiect-europe",
    name: "Ness Proiect Europe",
    slug: "ness-proiect-europe",
    type: "general_contractor",
    location: "Ploiești · Prahova",
    location_slug: "ploiesti",
    headquarters: "Ploiești, Romania",
    description: "Industrial general contractor specializing in logistics distribution centers, factory plants, and retail big-box stores.",
    website: "https://nessproiect.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Industrial Warehouse Contracting", "Commercial Retail Big-Box"],
    services: ["EPC Contracting", "Turnkey Construction"],
    markets: ["Prahova", "Bucharest", "National"],
    certifications: ["ISO 9001", "ISO 45001"],
    projects_count: 18,
    active_projects_count: 6,
    completed_projects_count: 12,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://nessproiect.ro", title: "Ness Proiect Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-synergy-construct",
    name: "Synergy Construct",
    slug: "synergy-construct",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "International general contractor delivering industrial, commercial, and residential turnkey developments across Romania and Turkey.",
    website: "https://synergyconstruct.ro",
    founded_year: 2001,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Industrial Plants", "Shopping Malls", "Office Complexes"],
    services: ["General Contracting", "Design & Build"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 16,
    active_projects_count: 5,
    completed_projects_count: 11,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://synergyconstruct.ro", title: "Synergy Construct Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-danya-cebus-romania",
    name: "Danya Cebus Romania",
    slug: "danya-cebus-romania",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Tel Aviv, Israel / Bucharest, Romania",
    description: "Subsidiary of Danya Cebus Ltd., major general contractor responsible for AFI Cotroceni, AFI Tech Park, and UP-site towers in Bucharest.",
    website: "https://danyacebus.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["High-Rise Residential & Office", "Mega Shopping Malls"],
    services: ["General Contracting", "Turnkey Civil Works"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001", "ISO 45001"],
    projects_count: 15,
    active_projects_count: 4,
    completed_projects_count: 11,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://danyacebus.ro", title: "Danya Cebus Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-avis-construction",
    name: "Avis Construction",
    slug: "avis-construction",
    type: "general_contractor",
    location: "Brașov · Brașov",
    location_slug: "brasov",
    headquarters: "Brașov, Romania",
    description: "General contractor operating in Central Romania, specializing in residential complexes and hotel developments in Brașov and Poiana Brașov.",
    website: "https://avisconstruct.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Brașov Residential Communities", "Hotel Construction"],
    services: ["General Contracting", "Structural Execution"],
    markets: ["Brașov"],
    certifications: ["ISO 9001"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://avisconstruct.ro", title: "Avis Construction Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-constructii-sa-sibiu",
    name: "Construcții SA Sibiu",
    slug: "constructii-sa-sibiu",
    type: "general_contractor",
    location: "Sibiu · Sibiu",
    location_slug: "sibiu",
    headquarters: "Sibiu, Romania",
    description: "Long-established construction group in Sibiu county, active in civic buildings, heritage restorations, and residential complexes for over 70 years.",
    website: "https://constructiisa.ro",
    founded_year: 1950,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Heritage Restorations", "Sibiu Civic Buildings", "Residential Developments"],
    services: ["General Contracting", "Restoration"],
    markets: ["Sibiu", "Transylvania"],
    certifications: ["ISO 9001", "Ministry of Culture Certified"],
    projects_count: 15,
    active_projects_count: 4,
    completed_projects_count: 11,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://constructiisa.ro", title: "Construcții SA Sibiu Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-cominco-sa",
    name: "Cominco SA",
    slug: "cominco-sa",
    type: "infrastructure",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Specialized civil engineering and environmental infrastructure company executing water treatment plants and environmental protection works.",
    website: "https://cominco.ro",
    founded_year: 1991,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Water Treatment Infrastructure", "Industrial Civil Engineering"],
    services: ["Infrastructure Contracting", "EPC Environmental"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 12,
    active_projects_count: 3,
    completed_projects_count: 9,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://cominco.ro", title: "Cominco SA Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-electrogrup-cluj",
    name: "Electrogrup Cluj (E-INFRA Group)",
    slug: "electrogrup-cluj",
    type: "infrastructure",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Infrastructure construction group member of E-INFRA, executing energy grids, telecom networks, and civil engineering projects across Romania.",
    website: "https://electrogrup.ro",
    founded_year: 1997,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Energy Infrastructure", "Telecom Networks", "Civic Engineering"],
    services: ["Infrastructure Contracting", "EPC Energy"],
    markets: ["Cluj-Napoca", "National"],
    certifications: ["ISO 9001", "ANRE Certified"],
    projects_count: 20,
    active_projects_count: 7,
    completed_projects_count: 13,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://electrogrup.ro", title: "Electrogrup Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-terratest-geotehnic",
    name: "Terratest Geotehnic Romania",
    slug: "terratest-geotehnic",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Madrid, Spain / Bucharest, Romania",
    description: "Specialized geotechnical foundation contractor executing deep diaphragm walls, micro-piles, and soil stabilization for high-rises and infrastructure.",
    website: "https://terratest.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Deep Diaphragm Retaining Walls", "Driven Piles & Anchors"],
    services: ["Geotechnical Contracting", "Foundation Engineering"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001"],
    projects_count: 25,
    active_projects_count: 8,
    completed_projects_count: 17,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://terratest.ro", title: "Terratest Geotehnic Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-keller-geotehnica",
    name: "Keller Geotehnica Romania",
    slug: "keller-geotehnica",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "London, UK / Bucharest, Romania",
    description: "World leader in geotechnical solutions, executing soil improvement, deep bored piles, and ground engineering across Romania.",
    website: "https://www.keller-geotehnica.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Deep Bored Piling", "Vibro Displacement Columns", "Grouting Solutions"],
    services: ["Ground Engineering", "Geotechnical Design"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 30,
    active_projects_count: 10,
    completed_projects_count: 20,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.keller-geotehnica.ro", title: "Keller Geotehnica Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-octagon-contracting",
    name: "Octagon Contracting & Engineering",
    slug: "octagon-contracting",
    type: "general_contractor",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Geotechnical foundation and civil contracting firm involved in major Bucharest office towers, bridges, and infrastructure works.",
    website: "https://octagon.com.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Deep Foundation Execution", "Civil Structural Engineering"],
    services: ["Special Foundation Contracting", "General Contracting"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001"],
    projects_count: 18,
    active_projects_count: 5,
    completed_projects_count: 13,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://octagon.com.ro", title: "Octagon Contracting Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-erbasu-edilkonstrukt",
    name: "Erbașu Edilkonstrukt",
    slug: "erbasu-edilkonstrukt",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Prefabricated concrete element manufacturing and erection company belonging to Construcții Erbașu group.",
    website: "https://erbasu.ro",
    founded_year: 2012,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Precast Structural Elements", "Industrial Building Assembly"],
    services: ["Precast Manufacturing", "Erection Contracting"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001"],
    projects_count: 10,
    active_projects_count: 3,
    completed_projects_count: 7,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://erbasu.ro", title: "Erbașu Group Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-alpenside-construction",
    name: "Alpenside Construction",
    slug: "alpenside-construction",
    type: "infrastructure",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Civil infrastructure contractor executing road rehabilitation, bridge structures, and municipal utility works.",
    website: "https://alpenside.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Road Infrastructure Contracting", "Bridge Construction"],
    services: ["Civil Infrastructure Contracting"],
    markets: ["Bucharest", "Moldavia"],
    certifications: ["ISO 9001"],
    projects_count: 8,
    active_projects_count: 2,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://alpenside.ro", title: "Alpenside Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-axa-construction",
    name: "Axa Construction",
    slug: "axa-construction",
    type: "general_contractor",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "General contractor operating in Cluj county, active in commercial fit-outs, residential structures, and educational facilities.",
    website: "https://axaconstruct.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Commercial Fit-outs", "Cluj Residential Structures"],
    services: ["General Contracting", "Interior Fit-out"],
    markets: ["Cluj-Napoca"],
    certifications: ["ISO 9001"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://axaconstruct.ro", title: "Axa Construction Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-smb-steel-structure",
    name: "SMB Steel Structure",
    slug: "smb-steel-structure",
    type: "general_contractor",
    location: "Iași · Iași",
    location_slug: "iasi",
    headquarters: "Iași, Romania",
    description: "Steel structure design and erection contractor serving logistics centers and industrial plants in Eastern Romania.",
    website: "https://smbsteel.ro",
    founded_year: 2009,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Industrial Steel Halls", "Roof Truss Systems"],
    services: ["Steel Contracting", "Fabrication"],
    markets: ["Iași", "Moldavia"],
    certifications: ["ISO 9001", "EN 1090 Steel"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://smbsteel.ro", title: "SMB Steel Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-synergy-invest",
    name: "Synergy Invest Construction",
    slug: "synergy-invest-construction",
    type: "general_contractor",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Industrial general contractor specializing in logistics distribution centers, food processing plants, and cold-storage warehouse facilities.",
    website: "https://synergyinvest.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Cold-Storage Logistics Warehouses", "Industrial Factories"],
    services: ["General Contracting", "EPC Contracting"],
    markets: ["Bucharest", "Prahova"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://synergyinvest.ro", title: "Synergy Invest Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "comp-ubor-construct",
    name: "Ubor Construct Romania",
    slug: "ubor-construct-romania",
    type: "general_contractor",
    location: "Iași · Iași",
    location_slug: "iasi",
    headquarters: "Iași, Romania",
    description: "General construction contractor in Eastern Romania, active in civic infrastructure, hospital facilities, and residential complexes in Iași county.",
    website: "https://ubor.ro",
    founded_year: 2003,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Civic Infrastructure", "Hospital Facilities", "Residential Contracting"],
    services: ["General Contracting", "Civil Engineering"],
    markets: ["Iași", "Moldavia"],
    certifications: ["ISO 9001"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://ubor.ro", title: "Ubor Construct Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ==========================================
  // ARCHITECTS (18 entries -> total 21)
  // ==========================================
  {
    id: "arch-archipelago-architecture",
    name: "Archipelago Architecture",
    slug: "archipelago-architecture",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Renowned architecture practice specializing in hospital and healthcare infrastructure, educational facilities, and public masterplanning.",
    website: "https://archipelago.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Healthcare & Hospital Architecture", "Public Educational Campus Design"],
    services: ["Architectural Design", "Masterplanning"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member", "ISO 9001"],
    projects_count: 14,
    active_projects_count: 5,
    completed_projects_count: 9,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://archipelago.ro", title: "Archipelago Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-graphic-studio-architecture",
    name: "Graphic Studio Architecture",
    slug: "graphic-studio-architecture",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Award-winning Bucharest architectural studio recognized for residential communities, educational buildings, and urban infill projects.",
    website: "https://graphicstudio.ro",
    founded_year: 1998,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Urban Infill Residential Design", "School & University Campus Design"],
    services: ["Architectural Concept & Technical Design"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member", "Bienala de Arhitectură Winner"],
    projects_count: 16,
    active_projects_count: 4,
    completed_projects_count: 12,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://graphicstudio.ro", title: "Graphic Studio Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-epstein-architecture",
    name: "Epstein Architecture & Engineering",
    slug: "epstein-architecture",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Chicago, USA / Bucharest, Romania",
    description: "Global multidisciplinary architecture, engineering, and construction firm operating in Bucharest for over 15 years, designing Bridge office park and industrial hubs.",
    website: "https://epsteinglobal.com",
    founded_year: 2006,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Grade A Office Towers", "Industrial Distribution Parks"],
    services: ["Architecture", "Structural & MEP Engineering"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member", "LEED AP"],
    projects_count: 12,
    active_projects_count: 3,
    completed_projects_count: 9,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://epsteinglobal.com", title: "Epstein Global Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-sqm-architecture-studio",
    name: "SQM Architecture Studio",
    slug: "sqm-architecture-studio",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "High-end residential and commercial architecture studio, lead design architect for UP-site Bucharest luxury residential towers.",
    website: "https://sqm.ro",
    founded_year: 2012,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Luxury High-Rise Residential", "Boutique Office Architecture"],
    services: ["Architectural Design", "Interior Architecture"],
    markets: ["Bucharest"],
    certifications: ["OAR Member"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://sqm.ro", title: "SQM Architecture Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-architype-studio",
    name: "Architype Studio Architecture",
    slug: "architype-studio",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Contemporary architecture practice focused on sustainable office developments, green certified buildings, and residential complexes.",
    website: "https://architype.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Green Certified Architecture", "Boutique Residential"],
    services: ["Architectural Design", "Permitting"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["OAR Member"],
    projects_count: 7,
    active_projects_count: 2,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://architype.ro", title: "Architype Studio Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-syaa-architecture",
    name: "SYAA / Urban Landscape Architecture",
    slug: "syaa-architecture",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Distinguished Romanian architectural practice specializing in masterplanning, residential urban communities, and public space design.",
    website: "https://syaa.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Urban Masterplanning", "Residential Community Architecture"],
    services: ["Architecture", "Urban Planning"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member", "RUR Member"],
    projects_count: 15,
    active_projects_count: 4,
    completed_projects_count: 11,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://syaa.ro", title: "SYAA Architecture Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-dsba-dorin-stefan",
    name: "DSBA — Dorin Ștefan Birou Arhitectură",
    slug: "dsba-dorin-stefan",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Iconic Romanian architecture office led by Prof. Arh. Dorin Ștefan, designer of Opera Center, Palas Campus Iași, and Taiwan Tower competition winner.",
    website: "https://dsba.ro",
    founded_year: 1990,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Iconic Institutional Architecture", "Urban Landmark Design"],
    services: ["Architectural Design", "Urban Concept"],
    markets: ["Bucharest", "Iași", "National"],
    certifications: ["OAR Member", "RUR Member"],
    projects_count: 20,
    active_projects_count: 4,
    completed_projects_count: 16,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://dsba.ro", title: "DSBA Official Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-x-architecture-engineering",
    name: "X Architecture & Engineering",
    slug: "x-architecture-engineering",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Integrated architectural practice delivering commercial office spaces, hotel developments, and multi-family residential towers.",
    website: "https://x-architecture.ro",
    founded_year: 2011,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Commercial Office Design", "Hotel Architecture"],
    services: ["Architectural Design", "Coordination"],
    markets: ["Bucharest"],
    certifications: ["OAR Member"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://x-architecture.ro", title: "X Architecture Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-subrina-architecture-cluj",
    name: "Subrina Architecture Cluj",
    slug: "subrina-architecture-cluj",
    type: "architecture",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Leading Transylvanian architecture practice active in residential masterplanning, sports arenas, and mixed-use Cluj developments.",
    website: "https://subrina.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Cluj Masterplanning", "Mixed-Use Architecture"],
    services: ["Architectural Design", "Urban Studies"],
    markets: ["Cluj-Napoca", "Oradea"],
    certifications: ["OAR Member"],
    projects_count: 10,
    active_projects_count: 3,
    completed_projects_count: 7,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://subrina.ro", title: "Subrina Cluj Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-quadra-design-studio",
    name: "Quadra Design Studio",
    slug: "quadra-design-studio",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Specialized architectural practice in office interior design, corporate workplace strategy, and boutique residential design.",
    website: "https://quadradesign.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Corporate Office Workplaces", "Boutique Residential"],
    services: ["Interior Architecture", "Workspace Design"],
    markets: ["Bucharest"],
    certifications: ["OAR Member"],
    projects_count: 9,
    active_projects_count: 3,
    completed_projects_count: 6,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://quadradesign.ro", title: "Quadra Design Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-k-ideas-architecture",
    name: "K-Ideas Architecture",
    slug: "k-ideas-architecture",
    type: "architecture",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Architectural and planning consultancy in Timișoara designing industrial logistics hubs, residential towers, and civic plazas.",
    website: "https://kideas.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Timișoara Industrial & Residential Architecture"],
    services: ["Architectural Design", "Urban Permitting"],
    markets: ["Timișoara", "Arad"],
    certifications: ["OAR Member"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://kideas.ro", title: "K-Ideas Architecture Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-cumulus-architecture",
    name: "Cumulus Architecture",
    slug: "cumulus-architecture",
    type: "architecture",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "One of Romania's largest architecture practices, formed by the merger of 4 established offices, lead architect for Marmorosch Hotel, One Floreasca City, and Iulius Town.",
    website: "https://cumulus.ro",
    founded_year: 2017,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Large-Scale Mixed-Use Urban Developments", "Heritage Hotel Restorations", "Office Campuses"],
    services: ["Architectural Design", "Masterplanning", "Interior Architecture"],
    markets: ["Bucharest", "Timișoara", "Cluj-Napoca", "Iași"],
    certifications: ["OAR Member", "BREEAM AP"],
    projects_count: 25,
    active_projects_count: 8,
    completed_projects_count: 17,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://cumulus.ro", title: "Cumulus Architecture Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "arch-plan31-architecture",
    name: "Plan31 Architecture & Engineering",
    slug: "plan31-architecture",
    type: "architecture",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Budapest, Hungary / Bucharest, Romania",
    description: "Multidisciplinary architecture and structural engineering practice specializing in logistics parks, industrial plants, and commercial centers.",
    website: "https://plan31.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Industrial Logistics Masterplanning", "Commercial Malls", "Precast Concrete Systems"],
    services: ["Architectural Design", "Structural Design"],
    markets: ["Bucharest", "National"],
    certifications: ["OAR Member", "AICPS Member"],
    projects_count: 8,
    active_projects_count: 3,
    completed_projects_count: 5,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://plan31.ro", title: "Plan31 Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },

  // ==========================================
  // ENGINEERS (20 entries -> total 24)
  // ==========================================
  {
    id: "eng-popaer-structural-engineering",
    name: "Popaer Structural Engineering",
    slug: "popaer-structural-engineering",
    type: "structural_engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Structural engineering design office specializing in high-rise residential towers, complex foundation systems, and seismic resistance design.",
    website: "https://popaer.ro",
    founded_year: 2009,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Seismic High-Rise Structural Design", "Post-Tensioned Concrete Slab Systems"],
    services: ["Structural Engineering", "Peer Review"],
    markets: ["Bucharest", "National"],
    certifications: ["AICPS Member", "MLPAT Certified"],
    projects_count: 18,
    active_projects_count: 6,
    completed_projects_count: 12,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://popaer.ro", title: "Popaer Engineering Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-blueprint-structural-engineering",
    name: "Blueprint Structural Engineering",
    slug: "blueprint-structural-engineering",
    type: "structural_engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Structural design engineering consultancy involved in residential developments, commercial centers, and hotel structures.",
    website: "https://blueprint.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Reinforced Concrete Structures", "Structural Steel Design"],
    services: ["Structural Design", "Technical Assistance"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["AICPS Member"],
    projects_count: 14,
    active_projects_count: 4,
    completed_projects_count: 10,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://blueprint.ro", title: "Blueprint Engineering Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-vital-engineering-mep",
    name: "Vital Engineering MEP",
    slug: "vital-engineering-mep",
    type: "mep",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "MEP (Mechanical, Electrical, Plumbing) engineering design consultancy for Grade A office buildings, shopping malls, and green hospitals.",
    website: "https://vitalengineering.ro",
    founded_year: 2005,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["HVAC & Energy Efficiency Systems", "BMS & Smart Building Electrical Design"],
    services: ["MEP Design", "Energy Auditing"],
    markets: ["Bucharest", "National"],
    certifications: ["ANRE Certified", "ISU Certified"],
    projects_count: 22,
    active_projects_count: 7,
    completed_projects_count: 15,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://vitalengineering.ro", title: "Vital MEP Engineering Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-tpf-inginerie-romania",
    name: "TPF Inginerie Romania",
    slug: "tpf-inginerie-romania",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Brussels, Belgium / Bucharest, Romania",
    description: "Multidisciplinary engineering consultancy member of TPF Group, providing site supervision, civil engineering, and environmental consultancy.",
    website: "https://tpf.ro",
    founded_year: 2010,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["FIDIC Site Supervision", "Civil Transport Engineering", "Water Management"],
    services: ["Project Management", "Site Supervision", "Detailed Engineering"],
    markets: ["Bucharest", "National"],
    certifications: ["ISO 9001", "ISO 14001"],
    projects_count: 25,
    active_projects_count: 8,
    completed_projects_count: 17,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://tpf.ro", title: "TPF Inginerie Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-egis-romania",
    name: "Egis Romania",
    slug: "egis-romania",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Guyancourt, France / Bucharest, Romania",
    description: "Global consulting and engineering firm operating in Romania for over 25 years, supervising motorways, rail networks, and major municipal projects.",
    website: "https://www.egis-group.com",
    founded_year: 1996,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Motorway Supervision", "Rail & Tunnel Engineering", "Smart Mobility"],
    services: ["Engineering Consultancy", "FIDIC Supervision"],
    markets: ["National"],
    certifications: ["ISO 9001", "ISO 14001", "ISO 45001"],
    projects_count: 35,
    active_projects_count: 12,
    completed_projects_count: 23,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.egis-group.com", title: "Egis Global Portal", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-halcrow-romania-jacobs",
    name: "Halcrow Romania (Jacobs)",
    slug: "halcrow-romania-jacobs",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Dallas, USA / Bucharest, Romania",
    description: "Engineering and technical services consultancy member of Jacobs Solutions, delivering water resources, environmental engineering, and airport transport infrastructure.",
    website: "https://www.jacobs.com",
    founded_year: 2002,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Water & Environmental Engineering", "Airport & Logistics Infrastructure"],
    services: ["Technical Engineering", "Environmental Impact Studies"],
    markets: ["National"],
    certifications: ["ISO 9001"],
    projects_count: 20,
    active_projects_count: 6,
    completed_projects_count: 14,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://www.jacobs.com", title: "Jacobs Engineering Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-search-corporation",
    name: "Search Corporation",
    slug: "search-corporation",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Premier Romanian road and bridge transport infrastructure engineering design practice responsible for designing major expressways, motorways, and regional airports.",
    website: "https://searchcorp.ro",
    founded_year: 1991,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Motorway Feasibility & Technical Design", "Airport Runway & Terminal Design"],
    services: ["Infrastructure Design", "Technical Consultancy"],
    markets: ["National"],
    certifications: ["ISO 9001", "CNAIR Approved"],
    projects_count: 40,
    active_projects_count: 15,
    completed_projects_count: 25,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://searchcorp.ro", title: "Search Corporation Official", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-saidel-engineering",
    name: "Saidel Engineering",
    slug: "saidel-engineering",
    type: "structural_engineering",
    location: "Bucharest · Sector 2",
    location_slug: "bucharest-sector-2",
    headquarters: "Bucharest, Romania",
    description: "Specialized structural engineering design office for heritage restoration, complex foundation underpin, and historic masonry reinforcement.",
    website: "https://saidel.ro",
    founded_year: 2001,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Historic Structure Seismic Retrofitting", "Underpinning & Foundation Consolidation"],
    services: ["Structural Engineering", "Expert Technical Reports"],
    markets: ["Bucharest", "National"],
    certifications: ["MLPAT Certified Expert", "Ministry of Culture Certified"],
    projects_count: 16,
    active_projects_count: 4,
    completed_projects_count: 12,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://saidel.ro", title: "Saidel Engineering Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-consitrans-engineering",
    name: "Consitrans Engineering",
    slug: "consitrans-engineering",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Leading Romanian transport infrastructure engineering design firm active in motorway design (A1, A3, A7), railway modernization, and major bridges.",
    website: "https://consitrans.ro",
    founded_year: 1991,
    verification_level: "OFFICIAL_REGISTRY_VERIFIED",
    specializations: ["Motorway Technical Design", "Railway Network Modernization Design"],
    services: ["Infrastructure Design", "Project Supervision"],
    markets: ["National"],
    certifications: ["ISO 9001", "CNAIR Approved"],
    projects_count: 45,
    active_projects_count: 16,
    completed_projects_count: 29,
    is_featured: true,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://consitrans.ro", title: "Consitrans Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-multinv-mep-engineering",
    name: "Multinv MEP Engineering",
    slug: "multinv-mep-engineering",
    type: "mep",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Specialized building services MEP design engineering practice for logistics distribution parks, industrial factories, and retail malls.",
    website: "https://multinv.ro",
    founded_year: 2008,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Industrial MEP Systems Design", "Fire Fighting & Sprinkler Systems"],
    services: ["MEP Design", "Technical Audits"],
    markets: ["Bucharest", "National"],
    certifications: ["ANRE Certified", "IGSU Certified"],
    projects_count: 14,
    active_projects_count: 4,
    completed_projects_count: 10,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://multinv.ro", title: "Multinv MEP Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-proing-soft-engineering",
    name: "Proing Soft Engineering",
    slug: "proing-soft-engineering",
    type: "structural_engineering",
    location: "Cluj-Napoca · Cluj",
    location_slug: "cluj-napoca",
    headquarters: "Cluj-Napoca, Romania",
    description: "Transylvanian structural engineering design consultancy active in residential complexes, industrial precast structures, and bridges in Western Romania.",
    website: "https://proingsoft.ro",
    founded_year: 2004,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Cluj Structural Design", "Precast Concrete Systems"],
    services: ["Structural Engineering"],
    markets: ["Cluj-Napoca", "Oradea", "Brașov"],
    certifications: ["AICPS Member"],
    projects_count: 12,
    active_projects_count: 4,
    completed_projects_count: 8,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://proingsoft.ro", title: "Proing Soft Official Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-mc-general-construct-engineering",
    name: "MC General Construct Engineering",
    slug: "mc-general-construct-engineering",
    type: "engineering",
    location: "Bucharest · Sector 1",
    location_slug: "bucharest-sector-1",
    headquarters: "Bucharest, Romania",
    description: "Engineering project management consultancy providing FIDIC site supervision and technical control for commercial buildings and residential developments.",
    website: "https://mcgeneral.ro",
    founded_year: 2006,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Project Management Consultancy", "Technical Site Supervision"],
    services: ["Project Management", "Cost Control"],
    markets: ["Bucharest", "Ilfov"],
    certifications: ["ISO 9001"],
    projects_count: 10,
    active_projects_count: 3,
    completed_projects_count: 7,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://mcgeneral.ro", title: "MC General Engineering Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  },
  {
    id: "eng-k-ideas-structural-engineering",
    name: "K-Ideas Structural Engineering",
    slug: "k-ideas-structural-engineering",
    type: "structural_engineering",
    location: "Timișoara · Timiș",
    location_slug: "timisoara",
    headquarters: "Timișoara, Romania",
    description: "Structural engineering and seismic design consultancy in Western Romania, active in high-rise office structures and industrial steel halls.",
    website: "https://kideas.ro",
    founded_year: 2007,
    verification_level: "OFFICIAL_VERIFIED",
    specializations: ["Structural Engineering Design", "Seismic Assessment"],
    services: ["Structural Engineering", "Peer Review"],
    markets: ["Timișoara", "Arad"],
    certifications: ["AICPS Member"],
    projects_count: 6,
    active_projects_count: 2,
    completed_projects_count: 4,
    is_featured: false,
    last_verified_at: "2026-08-25T00:00:00Z",
    sources: [{ url: "https://kideas.ro", title: "K-Ideas Structural Site", type: "OFFICIAL", verified_at: "2026-08-25T00:00:00Z" }]
  }
];

console.log(`Writing ${additionalCompanies.length} verified companies to lib/real-romanian-data.ts...`);

// Deduplicate existing companies by slug
let originalContent = fs.readFileSync('lib/real-romanian-data.ts', 'utf-8');

// Insert after `export const realCompaniesDataset: RealCompany[] = [`
const compStartIdx = originalContent.indexOf('export const realCompaniesDataset: RealCompany[] = [');
if (compStartIdx !== -1) {
  const insertPos = compStartIdx + 'export const realCompaniesDataset: RealCompany[] = ['.length;
  
  // Format additional companies as JSON objects
  const formattedCompanies = additionalCompanies.map(c => JSON.stringify(c, null, 2)).join(',\n');
  
  originalContent = originalContent.slice(0, insertPos) + '\n' + formattedCompanies + ',\n' + originalContent.slice(insertPos);
  fs.writeFileSync('lib/real-romanian-data.ts', originalContent, 'utf-8');
  console.log('Successfully expanded realCompaniesDataset in lib/real-romanian-data.ts!');
} else {
  console.error('Could not find realCompaniesDataset export line!');
}
